import type { Startup } from "./types";

/**
 * Everything the portfolio says about each product lives here. Sources are the
 * live sites and the products' own engineering trackers (September 2026). Keep
 * claims verifiable: build progress, shipped features and stated plan shapes —
 * never invented customer counts or revenue.
 */
export const startups: Startup[] = [
  {
    slug: "wonderhome",
    name: "WonderHome",
    tagline: "Smarter homes · Happier families",
    oneLiner:
      "An AI household operating system that manages the management — so families spend less time coordinating and more time together.",
    category: "Consumer · Family AI",
    audience: "Busy families with children, school, bills, help and a home to run",
    geography: "India-first, built for global households",
    stage: "Live product · early households onboarding",
    url: "https://home.wonderapps.biz/",
    helpUrl: "https://home.wonderapps.biz/help",
    accent: "oklch(0.49 0.09 190)",
    accentSoft: "oklch(0.93 0.03 190)",
    hero: {
      headline: "WonderHome takes care, so you can live more.",
      sub: "WonderHome watches the whole household — school, meals, groceries, bills, help, pets, health and family time, in text or voice — and interrupts the right person only when a decision is genuinely needed.",
    },
    problem: {
      title: "The management of life can consume the life itself.",
      lede: "Modern family life is beautiful, but it is a lot. Every existing tool adds another list for one parent — usually the same parent — to maintain.",
      points: [
        { title: "Invisible mental load", body: "Tasks, schedules, bills, shopping and school information never end, and they land disproportionately on one person." },
        { title: "Tools that add work", body: "Shared calendars, to-do apps and family chat groups all need feeding. None of them notice what is slipping." },
        { title: "Decisions at the wrong moment", body: "A bill is noticed when it is overdue. A science project is discovered the night before. Dinner is a question at 7 pm." },
        { title: "Trust is the barrier", body: "Families will not hand a home to software that acts without asking, or that treats children like adults." },
      ],
    },
    solution: {
      title: "It manages the management.",
      lede: "WonderHome does not give a family more things to manage. It holds household outcomes, resolves routine work where the family's policy permits, and asks — clearly, with a plan — before anything consequential.",
      pillars: [
        { title: "Outcomes, not chores", body: "A meal is 'ready by 8 pm', a bill is 'paid before the consequence', homework is 'finished with time to spare'. The system plans backwards from the outcome." },
        { title: "Asks before it acts", body: "Every consequential action shows what it understood, what it plans and the impact — with Confirm, Change and Cancel. Payments, deletions and access changes always ask." },
        { title: "Reads anything, corrects like a person", body: "Forward a whole school circular and every date, fee and item becomes its own tracked entry — a moved date updates in place, never a duplicate. 'No, almond milk' or 'Actually, make that Friday': WonderHome swaps or undoes what it did and keeps both steps on record." },
        { title: "One HomeTalk, every channel", body: "A single gateway carries the same household context everywhere. It's live on the web today; WhatsApp, Alexa and Gemini Live are built on the same gateway and switch on as each account is connected — payments and orders are never approved by voice." },
        { title: "Whole-household coverage, in eight languages", body: "Family & profiles, Today, School, Groceries, Meals, Bills, Househelper, Maintenance, Laundry, Pet care, Health & Fitness and Family time — one place, one assistant, text or voice. Every screen, reminder and HomeTalk reply in English, Hindi, Marathi, Spanish, French, German, Arabic or Mandarin, with each record keeping its own currency." },
        { title: "Private by design", body: "Tenant isolation is enforced in the database, children get age-appropriate views, health context needs its own explicit permission, and household data is never training data." },
      ],
    },
    howItWorks: [
      { step: "Observe", body: "Connected calendars, school portals, email and the family's own words tell WonderHome what is happening." },
      { step: "Understand & Plan", body: "Outcomes are checked against time, people and stock. A plan is drafted only when something is at risk." },
      { step: "Act (with consent)", body: "Routine work resolves silently within policy. Anything consequential returns as a plan the family confirms." },
      { step: "Monitor & Learn", body: "Notifications are sparse, threaded and resolve themselves. The household's preferences shape what comes next." },
    ],
    screens: [
      { src: "/screenshots/wonderhome/home-desktop.webp", alt: "WonderHome landing page on desktop showing the hero 'WonderHome takes care, so you can live more' and a household dashboard preview", kind: "desktop", caption: "The product site — same design language as the app" },
      { src: "/screenshots/wonderhome/home-mobile.webp", alt: "WonderHome on a phone, showing the mobile hero and Today view", kind: "mobile", caption: "Installs like an app on iPhone and Android" },
      { src: "/screenshots/wonderhome/features-desktop.webp", alt: "WonderHome features grid: 16 household domains from Family & Profiles to HomeSend and Your language", kind: "desktop", caption: "Sixteen features, each a household outcome" },
      { src: "/screenshots/wonderhome/security-desktop.webp", alt: "WonderHome security section: private by default, tenant isolation, child privacy, governed AI", kind: "desktop", caption: "Private by default — security as a family feature" },
    ],
    market: {
      title: "Every family is a household to run.",
      lede: "Dual-income, multi-generational homes with school-age children, domestic help and dense admin are the norm across India's metros and a fast-growing share of homes worldwide. They already pay for convenience — delivery, tutoring, help — but nobody sells them coordination.",
      segments: ["Urban dual-income families with school-age children", "Multi-generational households coordinating help and care", "Expat and NRI families running homes across time zones"],
      whyNow: [
        "Assistants that can plan and act — not just answer — became reliable enough to run background loops in 2025–26.",
        "Household commerce, school portals and calendars all now have programmatic surfaces to observe and act on.",
        "Consumer trust hinges on consent-first design; WonderHome's governed-tool architecture is built for exactly that.",
        "Voice assistants (Gemini Live, Alexa) and WhatsApp are wired to the same governed gateway and switch on the moment a household connects one — the scoped, revocable grant a household will actually trust.",
      ],
      figures: [
        { figure: "$16.29B", label: "Global AI assistant market, 2024, forecast $73.80B by 2033 at 18.8% CAGR",
          detail: "The closest defensible software category to WonderHome, with the publisher citing consumer demand for personalized, hands-free experiences as a driver.",
          source: { publisher: "Grand View Research", title: "AI Assistant Market Size And Share | Industry Report, 2033", url: "https://www.grandviewresearch.com/industry-analysis/ai-assistant-market-report", year: "2025" },
          note: "Base year 2024, CAGR 2025–2033. Covers consumer and enterprise assistants; publishers scope this market very differently." },
        { figure: "20.0 crore", label: "Women in employment in India (aged 15+), Jan-Dec 2025",
          detail: "Working women are the core of the time-poor buyer pool: 20.0 crore (200 million) women were employed in 2025.",
          source: { publisher: "MoSPI / NSO (Periodic Labour Force Survey Annual Report 2025)", title: "Press Note on Periodic Labour Force Survey Annual Report, 2025", url: "https://www.mospi.gov.in/uploads/latestReleases/latest_release_1774607827733_3e8964a9-268b-4cc9-ad65-cfc8a9e32f08_Press_note_AR_PLFS_2025_23032025_V2.1_26032026_final.pdf", year: "2026" },
          note: "Usual-status employment, calendar 2025. 1 crore = 10 million." },
        { figure: "85.5%", label: "Indian households with at least one smartphone (urban: 91.3%), early 2025",
          detail: "Nearly nine in ten Indian households already have a smartphone, and 86.3% have internet at home, so a text or voice assistant needs no new hardware.",
          source: { publisher: "MoSPI / NSO (Comprehensive Modular Survey: Telecom, 2025, NSS 80th round)", title: "Press Release: Results of Comprehensive Modular Survey: Telecom, 2025", url: "https://www.mospi.gov.in/sites/default/files/press_release/Final_press%20release_CMS_T.pdf", year: "2025" },
          note: "Survey of 34,950 households, January–March 2025. Urban households: 91.3%." },
        { figure: "305 min/day", label: "Time women aged 15-59 spend daily on unpaid domestic services (India, 2024)",
          detail: "Indian women in prime working age spend about five hours a day on unpaid household work; the NSO says this is down from 315 minutes in 2019.",
          source: { publisher: "MoSPI / NSO (Time Use Survey 2024)", title: "Press Note: Time Use Survey (TUS) January-December 2024", url: "https://mospi.gov.in/sites/default/files/press_release/PR_TUS_25022025.pdf", year: "2025" },
          note: "Per participant aged 15–59 in unpaid domestic services; down from 315 minutes in 2019." },
        { figure: "Over 50%", label: "Online adults in metro India who use generative AI, highest in Asia Pacific",
          detail: "Forrester finds metro India leads APAC on generative-AI use, and only 5% of metro Indians say they are not knowledgeable about AI.",
          source: { publisher: "Forrester", title: "Consumers Are Using AI - But They Still Don't Trust It", url: "https://www.forrester.com/blogs/consumers-are-using-ai-but-they-still-dont-trust-it/", year: "2025" },
          note: "Forrester gives “over half”, not an exact percentage. Sample is online adults in metro India." },
        { figure: "3.73 crore", label: "Overseas Indians (NRIs plus persons of Indian origin), as of January 2026: 37,280,845",
          detail: "MEA counts about 37.3 million Indians abroad (17.76M NRIs and 19.52M PIOs), the expat/NRI side of the buyer base.",
          source: { publisher: "Ministry of External Affairs, Government of India", title: "Population of Overseas Indians - Data on Indian Diaspora Abroad (as of January 2026)", url: "https://www.mea.gov.in/population-of-overseas-indians", year: "2026" },
          note: "NRIs 17.76 million plus persons of Indian origin 19.52 million, as of January 2026." },
      ],
    },
    businessModel: {
      title: "Consumer subscription with billing built end-to-end.",
      lede: "Three plans — Free, Pro and Max — with real prices set (Pro ₹299/month, Max ₹599/month). Billing for India and international customers, with refunds, is built and switches on when payments go live; every plan is free during early access until then.",
      plans: [
        { name: "Free", tagline: "Run the Home", bullets: ["Household basics with WonderHome watching quietly", "Outcomes, routines, notifications", "Maintenance, laundry, pet care", "Text conversation and background runs"] },
        { name: "Pro", tagline: "Let WonderHome Think", featured: true, bullets: ["The full household: school, commerce, meals, bills, family time", "Voice conversation", "School and homework intelligence", "Ordering and groceries"] },
        { name: "Max", tagline: "Let WonderHome Run the Home", bullets: ["Everything, with autonomous action", "Deeper integrations", "Highest usage limits"] },
      ],
    },
    moat: [
      { title: "Consent architecture", body: "Deterministic policy checks sit outside the model. Autonomy is set per household, per responsibility. This is hard to bolt on and is the reason families will let it act." },
      { title: "Household graph", body: "People, guardianship, protected time, stock levels, obligations, health context and preferences form a private, compounding model of one home." },
      { title: "Governed multi-channel voice", body: "A single HomeTalk contract, not a per-assistant bolt-on: linked voice identities carry hashed, scoped OAuth grants that activate as each assistant account is connected, and payments, orders and health changes are never reachable by voice alone." },
      { title: "Cost discipline", body: "Engineering guardrails target under US$2,000/month infrastructure at 10,000 active households and under US$0.75 of background AI per household per month." },
    ],
    traction: [
      { label: "Stories shipped", value: "223 / 225", note: "99.1% of a 24-module backlog, per the live tracker; one story waits on the owner and one was deliberately deferred" },
      { label: "Modules complete", value: "22 of 24", note: "Voice release gates need a real Alexa and Gemini Live run; right-to-left layouts are deferred" },
      { label: "Languages", value: "8", note: "English, Hindi, Marathi, Spanish, French, German, Arabic and Mandarin across every screen and HomeTalk" },
      { label: "Billing & payments", value: "India + international", note: "Checkout, refunds and reconciliation built; free during early access until payments go live" },
    ],
    roadmap: [
      { horizon: "Now", items: ["Turn on WhatsApp, Alexa and Gemini voice as each account is connected", "Voice release gates: a real Alexa and Gemini Live end-to-end run", "Activate payments as plans go live"] },
      { horizon: "Next", items: ["First partners on the developer platform (scoped keys and a sandbox are built)", "Right-to-left layouts on the remaining screens", "Forwarded-email intake once a receiving domain is set up"] },
      { horizon: "Later", items: ["Regional expansion beyond India", "More languages from the same catalog"] },
    ],
    ask: "Seeking design-partner families and early-stage investors who believe the household is the next operating system.",
    facts: [
      { label: "Platform", value: "Web · installs on iPhone, Android and desktop" },
      { label: "AI", value: "Plans and acts only with household consent" },
      { label: "Pricing", value: "Free · Pro · Max (no card for Free)" },
    ],
  },
  {
    slug: "wonderjobs",
    name: "WonderJobs",
    tagline: "Find. Grow. Belong.",
    oneLiner:
      "An AI career agent that searches real job sources, explains every match, prepares every application — and leaves the decisions to the candidate.",
    category: "Consumer · Career AI agent",
    audience: "Job seekers, career switchers, students and senior professionals",
    geography: "Global remote-first sources plus India via Adzuna",
    stage: "Live product · free plan · public demo",
    url: "https://jobs.wonderapps.biz/",
    helpUrl: "https://jobs.wonderapps.biz/help",
    accent: "oklch(0.55 0.23 285)",
    accentSoft: "oklch(0.94 0.04 285)",
    logo: { light: "/brands/wonderjobs/wonderjobs-logo-light.webp", dark: "/brands/wonderjobs/wonderjobs-logo-dark.webp", mark: "/brands/wonderjobs/wonder-mark.webp" },
    hero: {
      headline: "Your next opportunity is out there. Wonder finds it.",
      sub: "Tell Wonder what you're looking for, in your own words. It searches real job sources, explains every match, builds your résumé and fills the employer's form — you make the final call, and it never submits on anyone's behalf.",
    },
    problem: {
      title: "Job searching is a full-time job. It shouldn't be.",
      lede: "Candidates spend evenings re-typing the same details into the same forms, scanning the same boards and guessing whether a role is worth it.",
      points: [
        { title: "Repetition without signal", body: "The same listing appears on six boards. The same résumé is rewritten for the tenth time. None of it tells the candidate where they actually fit." },
        { title: "Opaque matching", body: "Boards rank by recency or by who paid. A candidate cannot see why a role appeared, or how strong the fit really is." },
        { title: "Automation that overreaches", body: "Auto-apply tools submit on the candidate's behalf, damaging reputation with employers and violating platform terms." },
        { title: "Ghost listings and noise", body: "Stale, duplicate and low-quality postings waste the scarcest resource a job seeker has: attention." },
      ],
    },
    solution: {
      title: "Find, decide, apply, progress — with the candidate in control.",
      lede: "The whole product is organised around outcomes, not screens: a plain-language search that shows what it read before running, cards that explain why a job surfaced and what to weigh, an Application Pack built only from materials that actually exist, and a progress view built from real applications — never a staged step.",
      pillars: [
        { title: "Career DNA, scored honestly", body: "Goal, level, years, rated skills, industries, locations, minimum salary, strengths and growth areas. Strong Opportunity (82+), Worth Considering (68+), Stretch (55+) — every score explained per dimension, and rescored when the profile changes." },
        { title: "JobsLake: a job-data layer, not a scraper", body: "A platform layer behind the search — canonical opportunities deduplicated across sources with per-field provenance, a REST/stream/MCP protocol, and an admin console with source health. 'Where this job was found' is always one click away." },
        { title: "Apply with Wonder, never on your behalf", body: "Fills the employer's own Greenhouse, Lever, Ashby or generic form through the candidate's browser — AI drafts, a guided mode, a downloadable pack — and stops for whatever only the candidate should answer. Structurally unable to submit; the candidate always does." },
        { title: "Résumé Studio", body: "Eight ATS-friendly templates rendered from one structured Career Profile, each a real PDF or Word download, plus a job-specific version generated straight from the Application Pack." },
        { title: "Your AI, your keys", body: "Use WonderJobs AI by default, or bring your own AI key. Keys are encrypted and never shown again." },
      ],
    },
    howItWorks: [
      { step: "Find", body: "One natural-language search, prefilled from the candidate's own goal. WonderJobs shows what it read and where from before it runs, against real sources through JobsLake." },
      { step: "Decide", body: "Every card says why Wonder surfaced it and what to weigh — never a bare score. Compare two to four jobs side by side; a hidden job says why, with a one-click override." },
      { step: "Apply", body: "An Application Pack opens only once real materials exist — tailored résumé, cover letter and screening answers, each labelled AI draft or the candidate's edit. Apply with Wonder fills the employer's form; the final action is always the candidate's." },
      { step: "Progress", body: "A home screen built from real applications and a real schedule — never a staged step or an invented number." },
    ],
    screens: [
      { src: "/screenshots/wonderjobs/home-desktop.webp", alt: "WonderJobs landing page on desktop: a plain-language search, today's priorities and an application ready for the candidate's final action", kind: "desktop", caption: "Scroll-linked hero on the product site" },
      { src: "/screenshots/wonderjobs/how-it-works-desktop.webp", alt: "WonderJobs Find, Decide, Apply, Progress outcome sections on desktop", kind: "desktop", caption: "Find · Decide · Apply · Progress — the whole app reorganised around outcomes" },
      { src: "/screenshots/wonderjobs/app-desktop.webp", alt: "WonderJobs Home dashboard showing what deserves the candidate's attention today", kind: "desktop", caption: "Home — what deserves your attention today" },
      { src: "/screenshots/wonderjobs/jobs-desktop.webp", alt: "WonderJobs jobs list in demo mode with fit labels, filters and why-surfaced reasons", kind: "desktop", caption: "Jobs view — every match explains itself" },
      { src: "/screenshots/wonderjobs/extension-desktop.webp", alt: "WonderJobs Apply with Wonder / browser extension page explaining what it fills and where it works", kind: "desktop", caption: "Apply with Wonder — fills the employer's own form, never submits it" },
      { src: "/screenshots/wonderjobs/applications-desktop.webp", alt: "WonderJobs applications dashboard with a needs-attention list and pipeline board", kind: "desktop", caption: "Applications — a real pipeline, not a spreadsheet" },
      { src: "/screenshots/wonderjobs/resume-studio-desktop.webp", alt: "WonderJobs Résumé Studio showing eight ATS-friendly templates", kind: "desktop", caption: "Résumé Studio — eight ATS-friendly templates, PDF or Word" },
      { src: "/screenshots/wonderjobs/home-mobile.webp", alt: "WonderJobs landing on a phone", kind: "mobile", caption: "Installable PWA" },
      { src: "/screenshots/wonderjobs/insights-desktop.webp", alt: "WonderJobs insights view in demo mode", kind: "desktop", caption: "Insights derived from real runs and applications" },
    ],
    market: {
      title: "Every active job seeker, every few years.",
      lede: "Job search is universal, recurring and painful. Incumbent boards monetise employers; the candidate side is under-served by tools that either spam or overreach. Remote-first hiring has widened the field a single person must scan.",
      segments: ["Knowledge workers searching remote and hybrid roles", "Career switchers who need fit explained, not assumed", "Students and early-career talent entering global markets", "Senior professionals managing a discreet, high-stakes search"],
      whyNow: [
        "Structured public job feeds and company ATS boards make honest, real-data search possible without scraping walled gardens.",
        "Language models draft credible, tailored materials — but only trustworthy when paired with deterministic matching and human approval.",
        "BYOK lets candidates pay their own AI bill, keeping the free tier genuinely free and gross margin high.",
      ],
      figures: [
        { figure: "$33.6B", label: "Global online recruitment market size in 2025, growing to $64.9B by 2031",
          detail: "Mordor Intelligence sizes the online recruitment market at $33.59B in 2025, forecasting 11.62% CAGR to 2031, with Asia Pacific the fastest-growing region.",
          source: { publisher: "Mordor Intelligence", title: "Online Recruitment Market Size & Share Analysis - Growth Trends and Forecast (2026 - 2031)", url: "https://www.mordorintelligence.com/industry-reports/online-recruitment-market", year: "2026" },
          note: "Forecast; base year 2025, CAGR 2026–2031." },
        { figure: "$15.2B by 2030", label: "Forecast global AI-in-HR market in 2030 (recruitment and hiring is the largest application)",
          detail: "Grand View Research values AI in HR at $3.2B in 2023 and projects $15.2B by 2030, a 24.8% CAGR, driven by automated sourcing, résumé screening and scheduling.",
          source: { publisher: "Grand View Research", title: "Artificial Intelligence In HR Market Size Report, 2024-2030", url: "https://www.grandviewresearch.com/industry-analysis/artificial-intelligence-hr-market-report", year: "2024" },
          note: "Forecast; base year 2023. Covers all of HR, of which recruiting is one application." },
        { figure: "~20%", label: "Share of job listings with no hiring activity in a given quarter (Greenhouse data)",
          detail: "Applicant-tracking vendor Greenhouse found about one in five listings never produced hiring activity, which is why seekers waste applications on 'ghost' postings.",
          source: { publisher: "SHRM (reporting Greenhouse Software data)", title: "Ghost Jobs: Real Concern or Phantom Phenomenon?", url: "https://www.shrm.org/topics-tools/news/talent-acquisition/ghost-jobs-fake-job-ads-phenomenon", year: "2024" },
          note: "Greenhouse data as relayed by SHRM. “No hiring activity” is not the same as a fake listing." },
        { figure: "74%", label: "US job seekers who personally use AI in their job search",
          detail: "A survey of 1,200 US job seekers found three in four already use AI, and 87% want employers to be transparent about their own AI use.",
          source: { publisher: "Greenhouse (hiring-software vendor survey)", title: "An AI Trust Crisis: 70% of Hiring Managers Trust AI to Make Faster and Better Hiring Decisions, Only 8% of Job Seekers Call it Fair (Greenhouse 2025 AI in Hiring Report)", url: "https://www.greenhouse.com/newsroom/an-ai-trust-crisis-70-of-hiring-managers-trust-ai-to-make-faster-and-better-hiring-decisions-only-8-of-job-seekers-call-it-fair", year: "2025" },
          note: "Vendor survey of 1,200 US job seekers, self-reported." },
        { figure: "39%", label: "Organisations that have implemented AI in HR functions; recruiting is the top use at 27%",
          detail: "SHRM's 2026 research finds under 40% of employers use AI in HR, led by recruiting, so employer-side AI screening is real but still early.",
          source: { publisher: "SHRM", title: "The State of AI in HR in 2026: 5 Critical Insights for CHROs", url: "https://www.shrm.org/executive-network/insights/state-of-ai-hr-2026-5-critical-insights-chros", year: "2026" },
          note: "SHRM research, 1,900+ HR professionals. Recruiting is the top use at 27%." },
        { figure: "15.9%", label: "India unemployment rate for ages 15-29, April-June 2026 (PLFS)",
          detail: "India's official quarterly labour survey puts youth unemployment at 15.9%, against 5.4% for all persons aged 15 and above, the largest cohort of early-career seekers.",
          source: { publisher: "National Statistics Office, MoSPI, Government of India", title: "Quarterly Bulletin, Periodic Labour Force Survey (PLFS), April - June 2026", url: "https://www.mospi.gov.in/uploads/publications_reports/publications_reports1786356638461_03375143-dcda-4a2e-89bf-036a8c7a87fc_PLFS_QB_April_June_2026.pdf", year: "2026" },
          note: "Official labour-force survey, all-India. Overall rate for ages 15+ was 5.4%." },
      ],
    },
    businessModel: {
      title: "Free to search. Pro for depth and automation.",
      lede: "The free plan is real and the demo runs without an account. Pro is the natural upgrade for scheduled runs, deeper coaching and higher limits; billing is designed but not yet connected, so today 'Upgrade' records interest. BYOK means heavy users can bring their own inference cost.",
      plans: [
        { name: "Free", tagline: "Search and prepare", bullets: ["Real sources, explainable matching", "Application materials and tracker", "WonderJobs AI or bring your own key", "Installable on any device"] },
        { name: "Pro", tagline: "In development", featured: true, bullets: ["Scheduled runs with a server-side scheduler", "Deeper résumé coaching and mock interviews", "Higher usage limits", "Priority sources as they land"] },
      ],
    },
    moat: [
      { title: "Honesty as a feature", body: "Only sources actually searched are shown. Illustrative scenarios are labelled. Wonder never submits on an employer's site — Apply with Wonder fills a form but is structurally unable to click submit. Trust compounds where competitors burn it." },
      { title: "JobsLake: infrastructure, not a feature", body: "Canonical opportunities deduplicated across sources with per-field provenance, a REST/stream/MCP protocol and source-health monitoring — the data layer a single-source competitor would have to rebuild from scratch." },
      { title: "Deterministic core, generative edge", body: "Matching, ranking and quality checks are rule-based and unit-tested; language models only draft prose. Cheap, auditable and consistent." },
      { title: "Scoped, ephemeral browser access", body: "Apply with Wonder never holds the account session in the browser helper. It mints a short-lived, read-only, HMAC-signed token that can't reach WonderJobs' own API and expires in 30 minutes." },
      { title: "Local-first, sync-second", body: "State hydrates locally and syncs per tenant in batches — fast on a phone, resilient offline, cheap to serve." },
    ],
    traction: [
      { label: "Epics complete", value: "11 / 15", note: "Remaining four are partial, with operator steps or provider config outstanding" },
      { label: "Apply with Wonder", value: "95 tests", note: "Including end-to-end runs against mock Greenhouse, Lever, Ashby and generic application forms" },
      { label: "Résumé Studio", value: "8 ATS templates", note: "PDF and Word downloads from one structured Career Profile, covered by automated tests" },
      { label: "Live job sources", value: "7 families", note: "Greenhouse/Lever/Ashby boards across 20+ companies plus six aggregators, now behind JobsLake" },
    ],
    roadmap: [
      { horizon: "Now", items: ["JobsLake production rollout and a real-account verification pass", "Email delivery for follow-ups and thank-you notes", "Google sign-in and a custom email sender"] },
      { horizon: "Next", items: ["Pro plan billing", "Chrome Web Store listing for Apply with Wonder", "Two-way calendar sync"] },
      { horizon: "Later", items: ["Additional regional sources", "Mock-interview AI and deeper coaching", "Platform admin for usage and key rotation"] },
    ],
    ask: "Seeking early-stage investors and distribution partners — universities, bootcamps and career services — who want candidates to have an agent of their own.",
    facts: [
      { label: "Platform", value: "Web · installable · desktop, tablet, mobile" },
      { label: "AI", value: "Drafts and explains; never submits for you" },
      { label: "Pricing", value: "Free today · Pro in development" },
    ],
  },
  {
    slug: "wondercreator",
    name: "Wonder Creator",
    tagline: "Everything begins with a little wonder.",
    oneLiner:
      "An AI-native creative studio where artists and creators keep their thoughts, photos and voice notes, see how they connect, and shape them into writing, carousels, images, video, audio and presentations — with every version, source and right kept on record.",
    category: "Consumer · Creator tools",
    audience: "Independent writers, photographers, filmmakers, musicians and designers, from hobbyists to working professionals",
    geography: "Global, browser-based",
    stage: "Live product · sign-up open",
    url: "https://creator.wonderapps.biz/",
    accent: "oklch(0.6 0.21 350)",
    accentSoft: "oklch(0.95 0.03 350)",
    logo: { light: "/brands/wondercreator/wondercreator-logo-light.webp", dark: "/brands/wondercreator/wondercreator-logo-dark.webp", mark: "/brands/wondercreator/wondercreator-mark.webp" },
    hero: {
      headline: "Everything begins with a little wonder.",
      sub: "Bring a thought, a photograph, a voice note or a link. CreativeMind sees how the pieces connect and suggests what they could become; you shape it in CreativeStudio, publish it to your own Creator Page, and keep every version, source and right.",
    },
    problem: {
      title: "Creators have more ideas than a place to keep, connect and finish them.",
      lede: "Raw material arrives as voice memos, photos, screenshots and half-sentences scattered across a dozen apps. Generic AI tools generate without remembering where anything came from, and social platforms reward engagement over craft.",
      points: [
        { title: "Scattered raw material", body: "Notes, photos, memos and links live in separate apps, so the connections between them are never seen." },
        { title: "AI that forgets its sources", body: "Generated drafts carry no record of which materials, versions or rights went into them." },
        { title: "Rights left to memory", body: "Who owns what, which licence applies and what was borrowed is tracked in someone's head, if at all." },
        { title: "Feedback ranked by vanity", body: "Likes and trending optimise for attention. Makers want honest, specific responses from people who care about the work." },
      ],
    },
    solution: {
      title: "A personal creative universe, with a studio inside.",
      lede: "Wonder Creator keeps everything a creator brings in, connects it, and helps shape it — with the creator in control of every consequential step.",
      pillars: [
        { title: "Capture anything", body: "Text, photos, voice notes, PDFs, Word files and links in one library, each with its provenance and a security check on upload." },
        { title: "CreativeMind suggests, never decides", body: "It finds connections across your material, offers directions with a reason, and only works on what you bring in. Anything touching rights, money or deletion waits for you." },
        { title: "CreativeStudio, every version kept", body: "A canvas for writing, carousels, images, video, audio and presentations. Versions are immutable and can be compared or restored, and a lineage graph shows what was made from what." },
        { title: "Rights on the record", body: "Ownership and joint shares, copyright and licences with terms, territory and dates, each change audited. Records, not legal advice." },
        { title: "Publish, collaborate, gather feedback", body: "A public Creator Page in a template that suits the work; Creative Rooms with crews, tasks and an attribution ledger; and Pulse, Communities and live Huddles — with no likes, no trending and no ranking." },
      ],
    },
    howItWorks: [
      { step: "Capture", body: "A note, a voice memo, a photo or a link — in a moment." },
      { step: "Discover", body: "CreativeMind notices how your pieces connect. Suggestions only." },
      { step: "Explore", body: "Look at a few directions before you choose one." },
      { step: "Create", body: "Bring sources into CreativeStudio and shape them on the canvas." },
      { step: "Refine", body: "Every version kept. Compare, restore, keep going." },
      { step: "Share", body: "Publish to your Creator Page, or ask Pulse what they think." },
    ],
    screens: [
      { src: "/screenshots/wondercreator/home-desktop.webp", alt: "Wonder Creator landing page: 'Everything begins with a little wonder' above a photo, a note, a voice memo and a carousel", kind: "desktop", caption: "A personal creative universe" },
      { src: "/screenshots/wondercreator/home-mobile.webp", alt: "Wonder Creator landing page on a phone", kind: "mobile", caption: "Made for the phone in your pocket" },
      { src: "/screenshots/wondercreator/studio-desktop.webp", alt: "CreativeStudio with four sources on the canvas and a CreativeMind suggestion to use two photos together", kind: "desktop", caption: "CreativeStudio, with CreativeMind beside you" },
      { src: "/screenshots/wondercreator/world-desktop.webp", alt: "Ideas, Materials, Moments, DejaVu and personal sources shown as small product scenes", kind: "desktop", caption: "Your world: ideas, materials, moments and sources" },
      { src: "/screenshots/wondercreator/journey-desktop.webp", alt: "The journey from Capture to Discover, Explore, Create, Refine and Share", kind: "desktop", caption: "From inspiration to Creation" },
      { src: "/screenshots/wondercreator/together-desktop.webp", alt: "Pulse, Communities and live Huddles", kind: "desktop", caption: "Feedback, not applause — no likes, no trending, no ranking" },
      { src: "/screenshots/wondercreator/publish-desktop.webp", alt: "A public Creator Page with a poem, a video, audio and a carousel each shown in its own form", kind: "desktop", caption: "A beautiful home for finished work" },
    ],
    market: {
      title: "Everyone who makes things is a creator now.",
      lede: "Creators are the fastest-growing independent workforce online, and generative AI is changing how they work. The tools they use are split between capture apps, editors and social platforms; none keeps the thread from first idea to published, rights-aware work.",
      segments: ["Independent writers, photographers and filmmakers", "Musicians and audio creators", "Designers and illustrators building a body of work", "Hobbyists who want to finish what they start"],
      whyNow: [
        "Generative AI makes drafting cheap, which makes provenance, version history and rights records more valuable, not less.",
        "Creators are looking for an alternative to engagement-ranked feeds: a calm place for feedback with no likes, trending or ranking.",
        "Provider-neutral AI lets the product follow the best models while the creator's material and rights stay put.",
      ],
      figures: [
        { figure: "$252.3B", label: "Global creator economy market size in 2025, forecast $1,345.5B by 2033",
          detail: "Grand View Research sizes the creator economy at $252.3B in 2025 and projects 23.3% annual growth to 2033.",
          source: { publisher: "Grand View Research", title: "Creator Economy Market Size, Share | Industry Report, 2033", url: "https://www.grandviewresearch.com/industry-analysis/creator-economy-market-report", year: "2026" },
          note: "Forecast; base year 2025, CAGR 2026–2033." },
        { figure: "$80.1B", label: "Generative AI in content creation market by 2030, growing 32.5% a year",
          detail: "Grand View sizes generative-AI content creation at $14.8B in 2024 and projects $80.1B by 2030.",
          source: { publisher: "Grand View Research", title: "Generative AI In Content Creation Market Report, 2025-2030", url: "https://www.grandviewresearch.com/industry-analysis/generative-ai-content-creation-market-report", year: "2026" },
          note: "Forecast; base year 2024, CAGR 2025–2030. Spans marketing, media, e-commerce and education." },
        { figure: "86%", label: "Share of creators actively using creative generative AI, Adobe survey of 16,000",
          detail: "Adobe's global survey found creative generative AI is already mainstream among emerging and semi-professional creators.",
          source: { publisher: "Adobe (survey by The Harris Poll)", title: "Inaugural Adobe Creators' Toolkit Report: 86 Percent of Global Creators Use Creative Generative AI, See it Boosting Creator Economy", url: "https://news.adobe.com/news/2025/10/adobe-max-2025-creators-survey", year: "2025" },
          note: "Survey of 16,000+ emerging and semi-professional creators in 8 countries." },
        { figure: "69%", label: "Creators concerned their content is used to train AI without permission",
          detail: "A clear majority of creators worry about consent over AI training, supporting a rights-first product stance.",
          source: { publisher: "Adobe (survey by The Harris Poll)", title: "Inaugural Adobe Creators' Toolkit Report: 86 Percent of Global Creators Use Creative Generative AI, See it Boosting Creator Economy", url: "https://news.adobe.com/news/2025/10/adobe-max-2025-creators-survey", year: "2025" },
          note: "Same Adobe survey. Self-reported." },
        { figure: "4%", label: "Share of global creators who earn over $100,000 a year (professionals)",
          detail: "Goldman's analysis shows only a small sliver of creators make a full living, so income concentration is the norm.",
          source: { publisher: "Goldman Sachs Research", title: "The creator economy could approach half-a-trillion dollars by 2027", url: "https://www.goldmansachs.com/insights/articles/the-creator-economy-could-approach-half-a-trillion-dollars-by-2027", year: "2023" },
          note: "Goldman’s own definition of professional, 2023 estimate." },
        { figure: "4.12 million", label: "India's creator base in 2025, up from 0.96 million in 2020",
          detail: "An ISB-Hashfame study finds India's creator base grew more than fourfold in five years, with 66% now outside metro markets.",
          source: { publisher: "Indian School of Business (SRITNE) with Hashfame", title: "India's Creator Economy Enters a New Phase as Non-Metro Creators Become the Majority, Reveals ISB-Hashfame Report", url: "https://www.isb.edu/news/press-releases/india-s-creator-economy-enters-a-new-phase-as-non-metro-creators-become-the-majority-reveals-isb-hashfame-report", year: "2026" },
          note: "ISB–Hashfame estimate. BCG counts a narrower 2–2.5 million monetised creators." },
      ],
    },
    businessModel: {
      title: "Free to start. Creator income built in.",
      lede: "No paid plan is published yet. The product is free to start and already contains the machinery a creator business needs: usage allowances per generation tier, bring-your-own AI key, a licensing marketplace built behind a flag, and licence-fee collection that switches on when payments go live. Revenue terms will be finalised with the first creators.",
      plans: [
        { name: "Creators", tagline: "Free to start", featured: true, bullets: ["Capture, connect, create and publish", "A public Creator Page", "Pulse, Communities and live Huddles", "Bring your own AI key, or use the platform's"] },
        { name: "Licensing & payments", tagline: "Built, provider-gated", bullets: ["Licences with terms, territory and dates", "Licence fees in INR and international currencies", "A creator-side income ledger", "A licence marketplace, built behind a flag"] },
      ],
    },
    moat: [
      { title: "Provenance by default", body: "Every material records where it came from, every version is immutable and every Creation has a lineage. That record is hard to retrofit and is what makes AI-assisted work trustworthy and licensable." },
      { title: "Governed AI, not autopilot", body: "CreativeMind only sees what the creator brings in, suggests rather than decides, and has hard ceilings for rights, commerce and destructive actions. Without a provider key the product says it is not connected rather than faking AI." },
      { title: "Designed against vanity metrics", body: "No likes, no trending, no ranking: a deliberate position against engagement-driven networks, expressed in Pulse, Communities and Huddles." },
    ],
    traction: [
      { label: "Tracked deliverables", value: "143 / 146", note: "97.9% done; 3 partial, none not started — from the product's own delivery log" },
      { label: "P0 capabilities", value: "24 built", note: "Identity, material, CreatorSend, CreatorTalk, CreatorBrain, Studio, versions, lineage, rights, Huddles and more; one partial" },
      { label: "Security tests (P0 gate)", value: "306 tests", note: "Authorisation and data-isolation tests against a real database, plus browser flows at desktop and 360px" },
      { label: "Product", value: "Live, sign-up open", note: "AI, live voice/video and payments switch on when their providers are connected; the product says 'not connected' until then" },
    ],
    roadmap: [
      { horizon: "Now", items: ["Connect and verify AI, live voice/video and payment providers in production", "Finish the UI redesign canvas across the remaining screens", "Complete CreatorPublish's remaining phases"] },
      { horizon: "Next", items: ["Open the licence marketplace (built, behind a flag)", "Brand partnerships on the campaign foundation", "Publication analytics from connected destinations"] },
      { horizon: "Later", items: ["Revenue splits for collaborations", "More creator business tools on the income ledger"] },
    ],
    ask: "Seeking early-stage investors and creator-economy partners who believe makers deserve a studio that remembers where their work came from.",
    facts: [
      { label: "Platform", value: "Web · installable on phone and desktop" },
      { label: "AI", value: "Suggests directions; you decide. Bring your own AI key" },
      { label: "Pricing", value: "Free to start · revenue terms being finalised" },
    ],
  },
  {
    slug: "wonderark",
    name: "WonderArk",
    tagline: "Business in one place.",
    oneLiner:
      "One login and one data model for a growing business: customer discovery, marketing, fundraising, inventory, field service, a shared inbox and accounting with GST — licensed module by module, never duplicating a customer, an item or an invoice.",
    category: "B2B · SMB operating platform",
    audience: "Growing businesses outgrowing spreadsheets and a pile of disconnected apps",
    geography: "India-first (GST-native), architecture is region-agnostic",
    stage: "Live platform · five modules, paid plans in readiness review",
    url: "https://ark.wonderapps.biz/",
    helpUrl: "https://ark.wonderapps.biz/help",
    accent: "oklch(0.605 0.217 257)",
    accentSoft: "oklch(0.94 0.035 257)",
    hero: {
      headline: "One login. Every part of your business. Zero duplicate data.",
      sub: "WonderArk replaces the pile of disconnected apps a growing business ends up with — discovery, marketing, fundraising, inventory, field service, a shared inbox and accounting with GST — with one portal where every module already knows your customers, your items and your team.",
    },
    problem: {
      title: "Growth turns into a pile of tools.",
      lede: "A business that starts on spreadsheets ends up with a CRM, an inventory app, a field-service tool, a chat inbox and a GST portal — five logins, five customer records, five inventory counts.",
      points: [
        { title: "Duplicate everything", body: "The same customer exists in the CRM, the invoicing tool and the WhatsApp inbox, with three different phone numbers." },
        { title: "Stock that disagrees", body: "The count in the inventory app never matches the parts a field crew actually used on a job." },
        { title: "Compliance by re-entry", body: "GST returns, e-invoices and e-way bills are re-keyed from sales data that already exists somewhere else." },
        { title: "Integration tax", body: "Every 'integration' is an export, an import and a person who owns the spreadsheet in between." },
      ],
    },
    solution: {
      title: "One portal. One account. Five modules. One truth.",
      lede: "A strictly bounded modular platform: a shared core schema owns every cross-module noun — parties, items, documents, payments, messages — and each module owns only what is genuinely its own.",
      pillars: [
        { title: "Discovery, Marketing & Funding", body: "Per business offering, AI builds the ideal customer profile, finds and scores real accounts and explains why now. Marketing (strategy, campaigns, AI content, SEO, analytics) and Funding (investor pipeline, readiness, data room, diligence) sit on the same data. AI researches; humans approve every outreach." },
        { title: "Inventory & Service", body: "Multi-warehouse stock, purchase and sales orders, returns; opportunity-to-job pipeline, crew dispatch calendar, mobile field work with time, notes and signatures, and job invoicing that consumes stock." },
        { title: "CRM", body: "A unified inbox across WhatsApp, email and more, routing rules, lead lifecycle and a follow-up queue — tied to the same customer record every other module uses." },
        { title: "Finance & GST", body: "Automatic posting from sales and purchases, statements with drill-down to the source document, cash flow, bank rules and reporting dimensions — and GST returns computed from actual sales data rather than re-entered." },
        { title: "A team, not a login", body: "Business-scoped roles and invitations, with every action checked against both the module licence and the person's permission. Every module exports to CSV or Excel." },
      ],
    },
    howItWorks: [
      { step: "Create the business once", body: "One signup, one login, one business record — or several businesses under one account." },
      { step: "License modules independently", body: "Start with one. Add or drop later. Cancelling never deletes data: a 30-day read-only grace, then rows are retained for reactivation." },
      { step: "Data connects automatically", body: "A prospect won in Discovery is the customer in Service. Parts consumed on a job move stock in Inventory. The invoice feeds GST." },
      { step: "Ask the platform", body: "A built-in assistant answers from live data across every module you have licensed, grounded in real records." },
    ],
    screens: [
      { src: "/screenshots/wonderark/home-desktop.webp", alt: "WonderArk landing page on desktop with the new brand: one login, every part of your business, zero duplicate data", kind: "desktop", caption: "Business in one place — the new WonderArk identity" },
      { src: "/screenshots/wonderark/home-mobile.webp", alt: "WonderArk landing on a phone", kind: "mobile", caption: "Responsive across devices" },
      { src: "/screenshots/wonderark/modules-desktop.webp", alt: "WonderArk Discovery module: scored prospects per offering, with Marketing and Funding alongside", kind: "desktop", caption: "Discovery now finds customers, markets to them and funds the growth" },
      { src: "/screenshots/wonderark/how-it-works-desktop.webp", alt: "WonderArk how-it-works: create the business once, license modules independently, data connects automatically", kind: "desktop", caption: "License what you need; add modules in place" },
    ],
    market: {
      title: "The mid-market between spreadsheets and SAP.",
      lede: "Businesses with a warehouse, a field crew, a sales pipeline and a tax identity — trades, distributors, installers, service companies — are too complex for a single-purpose app and too small for an enterprise suite. India's GST regime makes structured, compliant data non-optional.",
      segments: ["Field-service and installation businesses", "Distributors and traders managing multi-warehouse stock", "Founder-led B2B companies building their first pipeline", "Any GST-registered business filing from real sales data"],
      whyNow: [
        "E-invoicing and e-way bill mandates keep widening the set of businesses that must operate from clean, connected data.",
        "AI makes prospect research and multi-module querying practical for a business with no analyst.",
        "Modular licensing lets a customer start small and expand in place — the land-and-expand motion vertical SaaS lacks.",
      ],
      figures: [
        { figure: "31.1% of GDP", label: "MSME share of India's GDP, with 48.58% of exports (January 2026 data)",
          detail: "MSMEs are the second-largest employer in India after agriculture, so the addressable buyer base is both large and economically central.",
          source: { publisher: "Press Information Bureau (Government of India), MSME Day 2026 fact sheet", title: "From Enterprise to Empowerment: The MSME Story - Engines of Growth in a Changing Economy", url: "https://static.pib.gov.in/WriteReadData/specificdocs/documents/2026/jun/doc2026626903401.pdf", year: "2026" },
          note: "Government of India fact sheet, January 2026 data." },
        { figure: "8.7 crore", label: "Enterprises registered on Udyam Registration Portal and Udyam Assist Platform (June 2026)",
          detail: "Formal MSME registrations have reached 8.7 crore, a very large formalised base for a licensed multi-module business platform.",
          source: { publisher: "Press Information Bureau (Government of India), MSME Day 2026 fact sheet", title: "From Enterprise to Empowerment: The MSME Story - Engines of Growth in a Changing Economy", url: "https://static.pib.gov.in/WriteReadData/specificdocs/documents/2026/jun/doc2026626903401.pdf", year: "2026" },
          note: "Self-declared registrations, not a count of active businesses. 1 crore = 10 million." },
        { figure: "1.67 crore", label: "Active GST taxpayers in India as of 30 June 2026",
          detail: "The GST-registered base is the natural GST-native market; it has grown from 66.5 lakh in 2017.",
          source: { publisher: "Goods and Services Tax Network (GSTN)", title: "9 Years of GST: A Statistical Report on the Completion of Nine Years of GST (2017-2026)", url: "https://tutorial.gst.gov.in/offlineutilities/gst_statistics/9YearsReport.pdf", year: "2026" },
          note: "Net of cancellations. 1 crore = 10 million." },
        { figure: "~83.6%", label: "E-invoice share of GSTR-1 reported B2B invoice value, Jul 2025 - Jun 2026",
          detail: "E-invoicing now covers most reported invoice value, so GST-ready invoicing is becoming table stakes for growing SMBs.",
          source: { publisher: "Goods and Services Tax Network (GSTN)", title: "9 Years of GST: A Statistical Report on the Completion of Nine Years of GST (2017-2026)", url: "https://tutorial.gst.gov.in/offlineutilities/gst_statistics/9YearsReport.pdf", year: "2026" },
          note: "System-generated GSTN data, not audited. Share by value; by count it is about 67.8%." },
        { figure: "$1.07B", label: "India ERP market size in 2025, forecast $2.62B by 2031 (16.08% CAGR)",
          detail: "ERP demand in India is driven by GST and e-invoicing compliance, with SMEs the fastest-growing segment at a 19.2% CAGR.",
          source: { publisher: "Mordor Intelligence", title: "India Enterprise Resource Planning Market Size, Share & 2031 Growth Trends Report", url: "https://www.mordorintelligence.com/industry-reports/india-enterprise-resource-planning-market", year: "2026" },
          note: "Forecast; base year 2025. Other publishers define the market differently." },
        { figure: "$6.1B", label: "Global field service management market in 2025, forecast $13.8B by 2033 (11.0% CAGR)",
          detail: "Field service software is a growing standalone category, with SMEs the fastest-growing customer segment per the publisher.",
          source: { publisher: "Grand View Research", title: "Field Service Management Market Size Report, 2026-2033", url: "https://www.grandviewresearch.com/industry-analysis/field-service-management-market", year: "2026" },
          note: "Global, not India-only. Forecast; base year 2025, CAGR 2026–2033." },
      ],
    },
    businessModel: {
      title: "License by module. Expand in place.",
      lede: "Published pricing in Indian Rupees: Free, Pro at ₹2,999/month and Max at ₹9,999/month, plus AI credit packs (₹1,000 for 500 runs up to ₹6,000 for 4,000) or bring-your-own-key. Billing is built and in its production-readiness review, so Pro and Max are sold by conversation today. Licensing is enforced at every layer, so an unlicensed module is genuinely off, not merely hidden.",
      plans: [
        { name: "Free", tagline: "Start with discovery", bullets: ["Core discovery tools at no cost", "One login, one business", "Team members with roles and permissions"] },
        { name: "Pro", tagline: "₹2,999 / month", featured: true, bullets: ["Every module, more usage headroom", "Up to 200 AI runs a month per Discovery offering", "Cancel a module any time: 30 days read-only, data never deleted"] },
        { name: "Max", tagline: "₹9,999 / month", bullets: ["Highest limits and every feature", "For teams running at scale", "Credit packs or your own AI key on top"] },
      ],
    },
    moat: [
      { title: "The entity-ownership map", body: "A prospect, a customer and a supplier are one party row with several roles. An estimate, an invoice and a purchase order are one documents table. This anti-duplication contract is the product." },
      { title: "Books from the same records", body: "Statements and GST come from the same sales and stock records the operations run on, so the books and the business cannot drift apart." },
      { title: "Cancel-safe by design", body: "Licensing never deletes data and reactivation replays parked events — the confidence a business needs to try a module." },
    ],
    traction: [
      { label: "Stories complete", value: "519 / 626", note: "87% of in-scope work; 30 superseded and 3 deferred stories excluded. A story counts only when code cites it" },
      { label: "Modules", value: "5 on one schema", note: "Discovery (with Marketing and Funding), Inventory, Service, CRM, Finance — independently licensable" },
      { label: "Exports", value: "Every module", note: "CSV and Excel across all modules and platform admin — 89 of 90 export stories done" },
      { label: "Team access", value: "39 of 39", note: "Multi-user, multi-business roles and invitations, enforced alongside licensing" },
    ],
    roadmap: [
      { horizon: "Now", items: ["Billing production-readiness review, then self-serve paid plans", "Global tax: VAT/GST for UAE, Saudi Arabia, Australia, NZ and Southeast Asia", "Platform administration portal (26 stories left)"] },
      { horizon: "Next", items: ["E-invoice and e-way bill transaction lists and their exports", "Finish the offering-centric Discovery upgrade (6 stories left)", "CRM channel connectors (WhatsApp, email)"] },
      { horizon: "Later", items: ["Public API and partner integrations", "Independent deployability per module as scale demands"] },
    ],
    ask: "Seeking design customers in field service and distribution, and investors who understand vertical SaaS in India's GST-native SMB market.",
    facts: [
      { label: "Platform", value: "Web · responsive · mobile-friendly field work" },
      { label: "AI", value: "AI-assisted prospecting and queries; bring your own key or use ours" },
      { label: "Pricing", value: "Free · Pro (per module) · Max (bundle)" },
    ],
  },
  {
    slug: "wonderid",
    name: "WonderID",
    tagline: "Secure every identity. Human and AI.",
    oneLiner:
      "Vendor-neutral identity governance for everything that holds access — people, service accounts, applications and AI agents — starting with the identity nobody governs yet: the AI agent.",
    category: "Enterprise · Identity governance & security",
    audience: "CISOs, IAM and GRC teams governing people, machines and AI agents",
    geography: "Global enterprise",
    stage: "Live multi-tenant platform · formerly WonderAgent",
    url: "https://id.wonderapps.biz/",
    helpUrl: "https://id.wonderapps.biz/help",
    accent: "oklch(0.563 0.24 264)",
    accentSoft: "oklch(0.93 0.04 264)",
    logo: { light: "/brands/wonderid/wonderid-logo-light.webp", dark: "/brands/wonderid/wonderid-logo-dark.webp", mark: "/brands/wonderid/wonderid-mark.webp" },
    hero: {
      headline: "Govern every identity. Verify every access.",
      sub: "People, service accounts and AI agents all hold real access to real systems. WonderID makes each one a governed identity — starting with AI agents, where it compares what an agent SHOULD do, CAN do and DID, and raises an evidence-backed finding the moment they disagree. Read-only to start; your IAM stays the system of record.",
    },
    problem: {
      title: "AI agents got production access. Nobody gave them an identity.",
      lede: "An agent is provisioned like a service account, inherits access like a person, and acts continuously like neither. Most exist as untracked service accounts — alongside the people and machines no one has reconciled either.",
      points: [
        { title: "No owner", body: "Provisioned as SVC_FINANCEBOT_PRD by someone who has since changed teams. No business owner, no technical owner, nobody to approve a change." },
        { title: "Purpose that no control can read", body: "The agent's approved scope lives in a ticket, a design doc or someone's memory — never anywhere a control can evaluate." },
        { title: "Access far beyond purpose", body: "Nested groups, OAuth scopes and tool permissions add up to reach that nobody has computed, let alone certified." },
        { title: "Behaviour disconnected from identity", body: "Runtime logs sit in an observability tool keyed by service name, cut off from the entitlement and approval that allowed the action." },
      ],
    },
    solution: {
      title: "SHOULD. CAN. DID. — then every identity around it.",
      lede: "Agent governance stays at its core; the same deterministic engine now extends to a unified identity directory, application onboarding and self-service access — across the IAM platforms a customer already runs (Saviynt, Okta, Entra, custom IAM and MCP runtimes map into one canonical model).",
      pillars: [
        { title: "AI agent governance", body: "Every agent gets an owner, a purpose contract and a lifecycle state. Its approved purpose (SHOULD), effective access computed from real entitlements, roles, groups and OAuth scopes (CAN), and observed runtime behaviour (DID) are compared continuously; any divergence is a finding with evidence." },
        { title: "One directory for every identity", body: "Humans, external users, service accounts, applications, workloads, APIs and AI agents in one tenant-scoped directory — fed by authoritative sources through a validate, correlate, stage and apply reconciliation pipeline, with joiner, mover and leaver lifecycle." },
        { title: "Applications, onboarded properly", body: "An application catalog that surfaces unrecognised apps, onboarding that validates, simulates and needs a four-eyes approval before it goes live, and an account inventory that flags orphaned and dormant accounts. AI can draft an onboarding proposal from an OpenAPI spec; a person approves it." },
        { title: "Self-service access, real approvals", body: "A request catalog with per-item policies, multi-stage approval chains that forbid self-approval, and access packages that work the same for people and agents." },
        { title: "Risk, certification & evidence", body: "Deterministic scoring — never an LLM guess — for excessive access, unauthorised actions, sensitive-data violations and behavioural deviation. Certification campaigns produce auditor-ready evidence packs." },
      ],
    },
    howItWorks: [
      { step: "Connect", body: "Import identities, applications and access from existing IAM and authoritative sources, plus runtime events from MCP or REST. Connectors declare capabilities explicitly; read-only means read-only." },
      { step: "Declare purpose", body: "Name an owner, approved applications, approved data classes and approved actions. That contract becomes SHOULD." },
      { step: "Compare continuously", body: "Purpose, effective access and observed behaviour are evaluated by explicit rules. Findings carry the evidence that produced them." },
      { step: "Remediate with a human", body: "Every recommended revocation waits for a human to confirm, is recorded against the finding, and is re-evaluated once access changes." },
    ],
    screens: [
      { src: "/screenshots/wonderid/home-desktop.webp", alt: "WonderID product site on desktop: 'Govern every identity. Verify every access.' above a tenant overview", kind: "desktop", caption: "The product site — every identity governed, starting with AI agents" },
      { src: "/screenshots/wonderid/home-mobile.webp", alt: "WonderID product site on a phone with the tenant overview preview", kind: "mobile", caption: "The same, on a phone" },
      { src: "/screenshots/wonderid/product-desktop.webp", alt: "WonderID risk list ordered by severity and the governed AI agent inventory", kind: "desktop", caption: "Risk ordered by what to do first; an agent inventory that is actually governed" },
      { src: "/screenshots/wonderid/model-desktop.webp", alt: "WonderID SHOULD, CAN and DID comparison raising an excessive-access finding for FinanceBot", kind: "desktop", caption: "SHOULD · CAN · DID — a critical finding, with the evidence attached" },
      { src: "/screenshots/wonderid/platform-desktop.webp", alt: "WonderID platform capabilities: agent lifecycle, effective access, runtime assurance, risk, certification and IAM integration", kind: "desktop", caption: "A governance layer over the IAM you already run" },
      { src: "/screenshots/wonderid/signin-desktop.webp", alt: "WonderID sign-in page with the new brand lockup", kind: "desktop", caption: "The WonderID brand, rolled out across every surface" },
    ],
    market: {
      title: "Every identity is an attack surface — and most of them aren't people.",
      lede: "Enterprise IAM was built for employees. Service accounts, workloads and APIs already sprawl beyond them, and AI agents add autonomy on top. Security leaders need one answer to 'who and what has access, who owns it, why, and what did they do with it?' — and proof for auditors.",
      segments: ["Regulated enterprises in finance, healthcare and public sector", "Organisations rolling out MCP-based agent platforms", "IAM/IGA teams consolidating human, machine and agent identity governance", "GRC teams facing AI-specific audit requirements"],
      whyNow: [
        "Agent adoption is outpacing governance; MCP has standardised how agents reach tools, which makes runtime observation tractable.",
        "Regulators and auditors are asking for demonstrable control over AI systems, not policy documents.",
        "Incumbent IGA suites are strong on human identity and bolt agents on; a vendor-neutral layer that starts from the agent and keeps existing IAM as system of record is the low-friction path in.",
      ],
      figures: [
        { figure: "$25.96B", label: "Global IAM market size in 2025 (forecast $42.61B by 2030)",
          detail: "The identity and access management market the buyer already spends in is about $26B and growing about 10% a year, with non-human IAM flagged as the faster-growing segment.",
          source: { publisher: "MarketsandMarkets", title: "Identity and Access Management (IAM) Market - Global Forecast to 2030", url: "https://www.marketsandmarkets.com/Market-Reports/identity-access-management-market-1168.html", year: "2025" },
          note: "Forecast; base year 2025, CAGR 2025–2030. Includes access management, IGA and PAM." },
        { figure: "$8.0B", label: "Global identity governance and administration (IGA) market, 2024 (to $27.1B by 2033)",
          detail: "IGA, the category WonderID sits in, is a roughly $8B market forecast to more than triple by 2033.",
          source: { publisher: "Grand View Research", title: "Identity Governance And Administration Market Report, 2025-2033", url: "https://www.grandviewresearch.com/industry-analysis/identity-governance-administration-market-report", year: "2025" },
          note: "Forecast; base year 2024, CAGR 2025–2033. A segment of IAM; scopes differ by publisher." },
        { figure: "$9.45B", label: "Non-human identity (NHI) access management market, 2024 (to $18.71B by 2030)",
          detail: "Analysts already size machine and API identity access management as a separate, roughly $9B market growing about 12% a year.",
          source: { publisher: "MarketsandMarkets", title: "Non-Human Identity (NHI) Access Management Market worth USD 18.71 billion by 2030", url: "https://www.marketsandmarkets.com/PressReleases/non-human-identity-nhi-access-management.asp", year: "2025" },
          note: "Forecast; base year 2024, CAGR 2024–2030." },
        { figure: "109:1", label: "Machine identities (incl. AI agents) per human identity, 2026 survey",
          detail: "A 2026 survey of 2,900+ security leaders finds machine identities, now including AI agents, outnumber humans 109 to 1.",
          source: { publisher: "Palo Alto Networks (CyberArk Identity Security Landscape)", title: "2026 Identity Security Landscape", url: "https://www.paloaltonetworks.com/idira/idira-identity-security-landscape", year: "2026" },
          note: "Vendor-sponsored survey of 2,900+ security decision-makers." },
        { figure: "1 in 5", label: "Companies with a mature governance model for autonomous AI agents",
          detail: "Deloitte's global survey of 3,235 leaders finds agentic AI use is set to rise sharply while governance lags.",
          source: { publisher: "Deloitte", title: "The State of AI in the Enterprise - 2026 AI report", url: "https://www.deloitte.com/us/en/what-we-do/capabilities/applied-artificial-intelligence/content/state-of-ai-in-the-enterprise.html", year: "2026" },
          note: "Deloitte survey of 3,235 leaders in 24 countries." },
        { figure: "$4.99M", label: "Global average cost of a data breach, IBM 2026",
          detail: "IBM's 2026 report puts the global average breach at $4.99M, a record high, so excess access that widens a breach has a direct price.",
          source: { publisher: "IBM (with Ponemon Institute)", title: "IBM Study: One in Four Malicious Breaches are AI-Enabled, Costing Companies $6 Million on Average", url: "https://newsroom.ibm.com/2026-07-29-ibm-study-one-in-four-malicious-breaches-are-ai-enabled,-costing-companies-6-million-on-average", year: "2026" },
          note: "IBM and Ponemon, 602 organisations; breaches March 2025 to February 2026." },
      ],
    },
    businessModel: {
      title: "Enterprise SaaS, priced per tenant.",
      lede: "Multi-tenant from day one with a separate vendor-only platform-admin boundary for tenants, subscriptions, feature flags, usage and health. Deployment-ready today; commercial packaging follows the first design customers.",
      plans: [
        { name: "Pilot", tagline: "Read-only proof", bullets: ["Connect one IAM and one runtime source", "Discover and register agents", "First risk findings and a certification round"] },
        { name: "Enterprise", tagline: "Governance in production", featured: true, bullets: ["Unlimited identities and integrations", "Identity directory, application onboarding and self-service access", "SSO/MFA, scoped roles and permissions", "Certification, evidence packs and human-confirmed remediation"] },
      ],
    },
    moat: [
      { title: "Agent-first, identity-wide", body: "Incumbent suites bolt agents onto a human model. WonderID started from the agent — owner, purpose, effective access, observed behaviour — and extends outward, so an AI agent is a first-class identity rather than a column on a service-account table." },
      { title: "Deterministic by architecture", body: "No authorisation, risk, policy or remediation decision depends on a language model. AI writes advisory summaries and proposals only. That is an auditable promise competitors chasing 'AI security' cannot easily make." },
      { title: "Vendor-neutral canonical model", body: "Saviynt, SailPoint, Entra, Okta, custom IAM and MCP map into one model without any becoming the internal architecture." },
      { title: "Built to enterprise bar from line one", body: "Strict tenant isolation, an immutable audit trail, encrypted credentials and hardened sign-in from the first commit — verified by a dedicated QA module." },
    ],
    traction: [
      { label: "Stories complete", value: "193 / 245", note: "79% across 11 modules; the tracker grew by 74 stories when WonderID's identity roadmap was adopted" },
      { label: "WonderID roadmap", value: "14 of 36 done", note: "Identity directory, reconciliation, application onboarding, account inventory, requests, approvals and access packages shipped; 4 more partial" },
      { label: "Screens", value: "78 + 8", note: "Customer pages plus the vendor platform-admin console" },
    ],
    roadmap: [
      { horizon: "Now", items: ["Business and IT roles, preventive SoD and delegations", "Provisioning and deprovisioning pipeline", "Access ledger, imported-access classification and Rogue Access management"] },
      { horizon: "Next", items: ["Certification campaigns for every identity type", "Passkey (WebAuthn) sign-in and step-up", "WonderID Home and a My Access self-service portal"] },
      { horizon: "Later", items: ["Configuration Studio and a workflow designer", "An advisory-only WonderID AI assistant", "Partner and MSSP editions"] },
    ],
    ask: "Seeking two to three enterprise design partners with agents in production or an identity estate to consolidate, and investors focused on security and identity infrastructure.",
    facts: [
      { label: "Platform", value: "Web · responsive · vendor platform-admin console" },
      { label: "AI", value: "Advisory summaries only; decisions are rule-based" },
      { label: "Pricing", value: "Pilot · Enterprise (packaging with design partners)" },
    ],
  },
];

export const startupBySlug = (slug: string) => startups.find((s) => s.slug === slug);
