import type { Startup } from "./types";

/**
 * Everything the portfolio says about each product lives here. Sources are the
 * live sites and the products' own engineering trackers (September 2026). Keep
 * claims verifiable: build progress, shipped features and stated plan shapes —
 * never invented customer counts or revenue.
 */
export const startups: Startup[] = [
  {
    slug: "wonderhome",
    name: "WonderHome",
    tagline: "Smarter homes · Happier families",
    oneLiner:
      "An AI household operating system that manages the management — so families spend less time coordinating and more time together.",
    category: "Consumer · Family AI",
    audience: "Busy families with children, school, bills, help and a home to run",
    geography: "India-first, built for global households",
    stage: "Live product · early households onboarding",
    url: "https://home.wonderapps.biz/",
    helpUrl: "https://home.wonderapps.biz/help",
    accent: "oklch(0.49 0.09 190)",
    accentSoft: "oklch(0.93 0.03 190)",
    hero: {
      headline: "WonderHome takes care, so you can live more.",
      sub: "WonderHome watches the whole household — school, meals, groceries, bills, help, pets, health and family time, in text or voice — and interrupts the right person only when a decision is genuinely needed.",
    },
    problem: {
      title: "The management of life can consume the life itself.",
      lede: "Modern family life is beautiful, but it is a lot. Every existing tool adds another list for one parent — usually the same parent — to maintain.",
      points: [
        { title: "Invisible mental load", body: "Tasks, schedules, bills, shopping and school information never end, and they land disproportionately on one person." },
        { title: "Tools that add work", body: "Shared calendars, to-do apps and family chat groups all need feeding. None of them notice what is slipping." },
        { title: "Decisions at the wrong moment", body: "A bill is noticed when it is overdue. A science project is discovered the night before. Dinner is a question at 7 pm." },
        { title: "Trust is the barrier", body: "Families will not hand a home to software that acts without asking, or that treats children like adults." },
      ],
    },
    solution: {
      title: "It manages the management.",
      lede: "WonderHome does not give a family more things to manage. It holds household outcomes, resolves routine work where the family's policy permits, and asks — clearly, with a plan — before anything consequential.",
      pillars: [
        { title: "Outcomes, not chores", body: "A meal is 'ready by 8 pm', a bill is 'paid before the consequence', homework is 'finished with time to spare'. The system plans backwards from the outcome." },
        { title: "Asks before it acts", body: "Every consequential action shows what it understood, what it plans and the impact — with Confirm, Change and Cancel. Payments, deletions and access changes always ask." },
        { title: "Reads anything, corrects like a person", body: "Forward a whole school circular and every date, fee and item becomes its own tracked entry — a moved date updates in place, never a duplicate. 'No, almond milk' or 'Actually, make that Friday': WonderHome swaps or undoes what it did and keeps both steps on record." },
        { title: "One HomeTalk, every channel", body: "A single gateway carries the same household context everywhere. It's live on the web today; WhatsApp, Alexa and Gemini Live are built on the same gateway and switch on as each account is connected — payments and orders are never approved by voice." },
        { title: "Whole-household coverage, in eight languages", body: "Family & profiles, Today, School, Groceries, Meals, Bills, Househelper, Maintenance, Laundry, Pet care, Health & Fitness and Family time — one place, one assistant, text or voice. Every screen, reminder and HomeTalk reply in English, Hindi, Marathi, Spanish, French, German, Arabic or Mandarin, with each record keeping its own currency." },
        { title: "Private by design", body: "Tenant isolation is enforced in the database, children get age-appropriate views, health context needs its own explicit permission, and household data is never training data." },
      ],
    },
    howItWorks: [
      { step: "Observe", body: "Connected calendars, school portals, email and the family's own words tell WonderHome what is happening." },
      { step: "Understand & Plan", body: "Outcomes are checked against time, people and stock. A plan is drafted only when something is at risk." },
      { step: "Act (with consent)", body: "Routine work resolves silently within policy. Anything consequential returns as a plan the family confirms." },
      { step: "Monitor & Learn", body: "Notifications are sparse, threaded and resolve themselves. The household's preferences shape what comes next." },
    ],
    screens: [
      { src: "/screenshots/wonderhome/home-desktop.webp", alt: "WonderHome landing page on desktop showing the hero 'WonderHome takes care, so you can live more' and a household dashboard preview", kind: "desktop", caption: "The product site — same design language as the app" },
      { src: "/screenshots/wonderhome/home-mobile.webp", alt: "WonderHome on a phone, showing the mobile hero and Today view", kind: "mobile", caption: "Installs like an app on iPhone and Android" },
      { src: "/screenshots/wonderhome/features-desktop.webp", alt: "WonderHome features grid: 16 household domains from Family & Profiles to HomeSend and Your language", kind: "desktop", caption: "Sixteen features, each a household outcome" },
      { src: "/screenshots/wonderhome/pricing-mobile.webp", alt: "WonderHome plans on a phone: Free, Pro and Max", kind: "mobile", caption: "Three plans, from a quiet watcher to a home that runs itself" },
      { src: "/screenshots/wonderhome/security-desktop.webp", alt: "WonderHome security section: private by default, tenant isolation, child privacy, governed AI", kind: "desktop", caption: "Private by default — security as a family feature" },
    ],
    market: {
      title: "Every family is a household to run.",
      lede: "Dual-income, multi-generational homes with school-age children, domestic help and dense admin are the norm across India's metros and a fast-growing share of homes worldwide. They already pay for convenience — delivery, tutoring, help — but nobody sells them coordination.",
      segments: ["Urban dual-income families with school-age children", "Multi-generational households coordinating help and care", "Expat and NRI families running homes across time zones"],
      whyNow: [
        "Assistants that can plan and act — not just answer — became reliable enough to run background loops in 2025–26.",
        "Household commerce, school portals and calendars all now have programmatic surfaces to observe and act on.",
        "Consumer trust hinges on consent-first design; WonderHome's governed-tool architecture is built for exactly that.",
        "Voice assistants (Gemini Live, Alexa) and WhatsApp are wired to the same governed gateway and switch on the moment a household connects one — the scoped, revocable grant a household will actually trust.",
      ],
    },
    businessModel: {
      title: "Consumer subscription with billing built end-to-end.",
      lede: "Plans are data, not code: Free, Pro and Max are rows in a live catalogue with server-side entitlements and atomic usage metering already shipped. Multi-provider billing (Razorpay for India, Stripe internationally) is code-complete — real prices seeded (Pro ₹299/month, Max ₹599/month), checkout, webhooks and a refund ledger all built — and switches on the moment a provider's keys are set; every plan is free during early access until then.",
      plans: [
        { name: "Free", tagline: "Run the Home", bullets: ["Household basics with WonderHome watching quietly", "Outcomes, routines, notifications", "Maintenance, laundry, pet care", "Text conversation and background runs"] },
        { name: "Pro", tagline: "Let WonderHome Think", featured: true, bullets: ["The full household: school, commerce, meals, bills, family time", "Voice conversation", "School and homework intelligence", "Ordering and groceries"] },
        { name: "Max", tagline: "Let WonderHome Run the Home", bullets: ["Everything, with autonomous action", "Deeper integrations", "Highest usage limits"] },
      ],
    },
    moat: [
      { title: "Consent architecture", body: "Deterministic policy checks sit outside the model. Autonomy is set per household, per responsibility. This is hard to bolt on and is the reason families will let it act." },
      { title: "Household graph", body: "People, guardianship, protected time, stock levels, obligations, health context and preferences form a private, compounding model of one home." },
      { title: "Governed multi-channel voice", body: "A single HomeTalk contract, not a per-assistant bolt-on: linked voice identities carry hashed, scoped OAuth grants that activate as each assistant account is connected, and payments, orders and health changes are never reachable by voice alone." },
      { title: "Cost discipline", body: "Engineering guardrails target under US$2,000/month infrastructure at 10,000 active households and under US$0.75 of background AI per household per month." },
    ],
    traction: [
      { label: "Stories shipped", value: "223 / 225", note: "99.1% of a 24-module backlog, per the live tracker; one story waits on the owner and one was deliberately deferred" },
      { label: "Modules complete", value: "22 of 24", note: "Voice release gates need a real Alexa and Gemini Live run; right-to-left layouts are deferred" },
      { label: "Languages", value: "8", note: "English, Hindi, Marathi, Spanish, French, German, Arabic and Mandarin across every screen and HomeTalk" },
      { label: "Billing & payments", value: "Razorpay + Stripe", note: "Checkout, webhooks, refunds and nightly reconciliation code-complete; free during early access until provider keys are set" },
    ],
    roadmap: [
      { horizon: "Now", items: ["Turn on WhatsApp, Alexa and Gemini voice as each account is connected", "Voice release gates: a real Alexa and Gemini Live end-to-end run", "Activate payments (Razorpay/Stripe) as plans go live"] },
      { horizon: "Next", items: ["First partners on the developer platform (scoped keys and a sandbox are built)", "Right-to-left layouts on the remaining screens", "Forwarded-email intake once a receiving domain is set up"] },
      { horizon: "Later", items: ["Regional expansion beyond India", "More languages from the same catalog"] },
    ],
    ask: "Seeking design-partner families and early-stage investors who believe the household is the next operating system.",
    facts: [
      { label: "Platform", value: "Web · PWA · iPhone · Android · Desktop" },
      { label: "AI", value: "Anthropic Claude primary; Gemini and OpenAI supported; BYOK" },
      { label: "Data", value: "Supabase PostgreSQL, RLS per household, ap-south-1" },
      { label: "Pricing", value: "Free · Pro · Max (no card for Free)" },
    ],
  },
  {
    slug: "wonderjobs",
    name: "WonderJobs",
    tagline: "Find. Grow. Belong.",
    oneLiner:
      "An AI career agent that searches real job sources, explains every match, prepares every application — and leaves the decisions to the candidate.",
    category: "Consumer · Career AI agent",
    audience: "Job seekers, career switchers, students and senior professionals",
    geography: "Global remote-first sources plus India via Adzuna",
    stage: "Live product · free plan · public demo",
    url: "https://jobs.wonderapps.biz/",
    helpUrl: "https://jobs.wonderapps.biz/help",
    accent: "oklch(0.55 0.23 285)",
    accentSoft: "oklch(0.94 0.04 285)",
    logo: { light: "/brands/wonderjobs/wonderjobs-logo-light.webp", dark: "/brands/wonderjobs/wonderjobs-logo-dark.webp", mark: "/brands/wonderjobs/wonder-mark.webp" },
    hero: {
      headline: "Your next opportunity is out there. Wonder finds it.",
      sub: "Tell Wonder what you're looking for, in your own words. It searches real job sources, explains every match, builds your résumé and fills the employer's form — you make the final call, and it never submits on anyone's behalf.",
    },
    problem: {
      title: "Job searching is a full-time job. It shouldn't be.",
      lede: "Candidates spend evenings re-typing the same details into the same forms, scanning the same boards and guessing whether a role is worth it.",
      points: [
        { title: "Repetition without signal", body: "The same listing appears on six boards. The same résumé is rewritten for the tenth time. None of it tells the candidate where they actually fit." },
        { title: "Opaque matching", body: "Boards rank by recency or by who paid. A candidate cannot see why a role appeared, or how strong the fit really is." },
        { title: "Automation that overreaches", body: "Auto-apply tools submit on the candidate's behalf, damaging reputation with employers and violating platform terms." },
        { title: "Ghost listings and noise", body: "Stale, duplicate and low-quality postings waste the scarcest resource a job seeker has: attention." },
      ],
    },
    solution: {
      title: "Find, decide, apply, progress — with the candidate in control.",
      lede: "The whole product is organised around outcomes, not screens: a plain-language search that shows what it read before running, cards that explain why a job surfaced and what to weigh, an Application Pack built only from materials that actually exist, and a progress view built from real applications — never a staged step.",
      pillars: [
        { title: "Career DNA, scored honestly", body: "Goal, level, years, rated skills, industries, locations, minimum salary, strengths and growth areas. Strong Opportunity (82+), Worth Considering (68+), Stretch (55+) — every score explained per dimension, and rescored when the profile changes." },
        { title: "JobsLake: a job-data layer, not a scraper", body: "A platform layer behind the search — canonical opportunities deduplicated across sources with per-field provenance, a REST/stream/MCP protocol, and an admin console with source health. 'Where this job was found' is always one click away." },
        { title: "Apply with Wonder, never on your behalf", body: "Fills the employer's own Greenhouse, Lever, Ashby or generic form through the candidate's browser — AI drafts, a guided mode, a downloadable pack — and stops for whatever only the candidate should answer. Structurally unable to submit; the candidate always does." },
        { title: "Résumé Studio", body: "Eight ATS-friendly templates rendered from one structured Career Profile, each a real PDF or Word download, plus a job-specific version generated straight from the Application Pack." },
        { title: "Your AI, your keys", body: "WonderJobs AI (Anthropic Claude) by default, or bring an Anthropic, OpenAI or Gemini key. Keys are AES-256-GCM encrypted, used only server-side, never returned." },
      ],
    },
    howItWorks: [
      { step: "Find", body: "One natural-language search, prefilled from the candidate's own goal. WonderJobs shows what it read and where from before it runs, against real sources through JobsLake." },
      { step: "Decide", body: "Every card says why Wonder surfaced it and what to weigh — never a bare score. Compare two to four jobs side by side; a hidden job says why, with a one-click override." },
      { step: "Apply", body: "An Application Pack opens only once real materials exist — tailored résumé, cover letter and screening answers, each labelled AI draft or the candidate's edit. Apply with Wonder fills the employer's form; the final action is always the candidate's." },
      { step: "Progress", body: "A home screen built from real applications and a real schedule — never a staged step or an invented number." },
    ],
    screens: [
      { src: "/screenshots/wonderjobs/home-desktop.webp", alt: "WonderJobs landing page on desktop: a plain-language search, today's priorities and an application ready for the candidate's final action", kind: "desktop", caption: "Scroll-linked hero on the product site" },
      { src: "/screenshots/wonderjobs/how-it-works-desktop.webp", alt: "WonderJobs Find, Decide, Apply, Progress outcome sections on desktop", kind: "desktop", caption: "Find · Decide · Apply · Progress — the whole app reorganised around outcomes" },
      { src: "/screenshots/wonderjobs/outcome-mobile.webp", alt: "WonderJobs Find, Decide, Apply, Progress outcome sections on a phone", kind: "mobile", caption: "The same outcomes, on mobile" },
      { src: "/screenshots/wonderjobs/app-desktop.webp", alt: "WonderJobs Home dashboard showing what deserves the candidate's attention today", kind: "desktop", caption: "Home — what deserves your attention today" },
      { src: "/screenshots/wonderjobs/jobs-desktop.webp", alt: "WonderJobs jobs list in demo mode with fit labels, filters and why-surfaced reasons", kind: "desktop", caption: "Jobs view — every match explains itself" },
      { src: "/screenshots/wonderjobs/extension-desktop.webp", alt: "WonderJobs Apply with Wonder / browser extension page explaining what it fills and where it works", kind: "desktop", caption: "Apply with Wonder — fills the employer's own form, never submits it" },
      { src: "/screenshots/wonderjobs/extension-mobile.webp", alt: "WonderJobs Apply with Wonder page on a phone", kind: "mobile", caption: "Install it from the landing page or any application" },
      { src: "/screenshots/wonderjobs/applications-desktop.webp", alt: "WonderJobs applications dashboard with a needs-attention list and pipeline board", kind: "desktop", caption: "Applications — a real pipeline, not a spreadsheet" },
      { src: "/screenshots/wonderjobs/resume-studio-desktop.webp", alt: "WonderJobs Résumé Studio showing eight ATS-friendly templates", kind: "desktop", caption: "Résumé Studio — eight ATS-friendly templates, PDF or Word" },
      { src: "/screenshots/wonderjobs/career-dna-mobile.webp", alt: "WonderJobs Career Profile on a phone", kind: "mobile", caption: "Career Profile — what every match, ranking and draft starts from" },
      { src: "/screenshots/wonderjobs/runs-mobile.webp", alt: "WonderJobs Wonder tab on a phone showing search history and scheduled searches", kind: "mobile", caption: "Wonder — search history and what it found, on mobile" },
      { src: "/screenshots/wonderjobs/home-mobile.webp", alt: "WonderJobs landing on a phone", kind: "mobile", caption: "Installable PWA" },
      { src: "/screenshots/wonderjobs/insights-desktop.webp", alt: "WonderJobs insights view in demo mode", kind: "desktop", caption: "Insights derived from real runs and applications" },
      { src: "/screenshots/wonderjobs/ai-mobile.webp", alt: "WonderJobs AI provider section on a phone: WonderJobs AI or bring your own Anthropic, OpenAI or Gemini key", kind: "mobile", caption: "Your AI, your keys" },
    ],
    market: {
      title: "Every active job seeker, every few years.",
      lede: "Job search is universal, recurring and painful. Incumbent boards monetise employers; the candidate side is under-served by tools that either spam or overreach. Remote-first hiring has widened the field a single person must scan.",
      segments: ["Knowledge workers searching remote and hybrid roles", "Career switchers who need fit explained, not assumed", "Students and early-career talent entering global markets", "Senior professionals managing a discreet, high-stakes search"],
      whyNow: [
        "Structured public job feeds and company ATS boards make honest, real-data search possible without scraping walled gardens.",
        "Language models draft credible, tailored materials — but only trustworthy when paired with deterministic matching and human approval.",
        "BYOK lets candidates pay their own AI bill, keeping the free tier genuinely free and gross margin high.",
      ],
    },
    businessModel: {
      title: "Free to search. Pro for depth and automation.",
      lede: "The free plan is real and the demo runs without an account. Pro is the natural upgrade for scheduled runs, deeper coaching and higher limits; billing is designed but not yet connected, so today 'Upgrade' records interest. BYOK means heavy users can bring their own inference cost.",
      plans: [
        { name: "Free", tagline: "Search and prepare", bullets: ["Real sources, explainable matching", "Application materials and tracker", "WonderJobs AI or bring your own key", "Installable on any device"] },
        { name: "Pro", tagline: "In development", featured: true, bullets: ["Scheduled runs with a server-side scheduler", "Deeper résumé coaching and mock interviews", "Higher usage limits", "Priority sources as they land"] },
      ],
    },
    moat: [
      { title: "Honesty as a feature", body: "Only sources actually searched are shown. Illustrative scenarios are labelled. Wonder never submits on an employer's site — Apply with Wonder fills a form but is structurally unable to click submit. Trust compounds where competitors burn it." },
      { title: "JobsLake: infrastructure, not a feature", body: "Canonical opportunities deduplicated across sources with per-field provenance, a REST/stream/MCP protocol and source-health monitoring — the data layer a single-source competitor would have to rebuild from scratch." },
      { title: "Deterministic core, generative edge", body: "Matching, ranking and quality checks are rule-based and unit-tested; language models only draft prose. Cheap, auditable and consistent." },
      { title: "Scoped, ephemeral browser access", body: "Apply with Wonder never holds the account session in the browser helper. It mints a short-lived, read-only, HMAC-signed token that can't reach WonderJobs' own API and expires in 30 minutes." },
      { title: "Local-first, sync-second", body: "State hydrates locally and syncs per tenant in batches — fast on a phone, resilient offline, cheap to serve." },
    ],
    traction: [
      { label: "Epics complete", value: "11 / 15", note: "Remaining four are partial, with operator steps or provider config outstanding" },
      { label: "Apply with Wonder", value: "95 tests", note: "75 unit/API + 20 Playwright end-to-end on mock Greenhouse, Lever, Ashby and generic ATS forms" },
      { label: "Résumé Studio", value: "8 ATS templates", note: "PDF and Word downloads from one structured Career Profile; 304 unit + 30 Playwright tests" },
      { label: "Live job sources", value: "7 families", note: "Greenhouse/Lever/Ashby boards across 20+ companies plus six aggregators, now behind JobsLake" },
    ],
    roadmap: [
      { horizon: "Now", items: ["JobsLake production rollout: pending migration and a real-account verification pass", "Email delivery for follow-ups and thank-you notes", "Custom SMTP and Google sign-in provider configuration"] },
      { horizon: "Next", items: ["Pro plan billing", "Chrome Web Store listing for Apply with Wonder", "Two-way calendar sync"] },
      { horizon: "Later", items: ["Additional regional sources", "Mock-interview AI and deeper coaching", "Platform admin for usage and key rotation"] },
    ],
    ask: "Seeking early-stage investors and distribution partners — universities, bootcamps and career services — who want candidates to have an agent of their own.",
    facts: [
      { label: "Platform", value: "Web · PWA · desktop, tablet, mobile" },
      { label: "AI", value: "Anthropic Claude (platform) · Anthropic / OpenAI / Gemini BYOK" },
      { label: "Data", value: "Supabase PostgreSQL, dedicated schema, RLS, service-role only" },
      { label: "Pricing", value: "Free today · Pro in development" },
    ],
  },
  {
    slug: "wonderark",
    name: "WonderArk",
    tagline: "Business in one place.",
    oneLiner:
      "One login and one data model for a growing business: customer discovery, marketing, fundraising, inventory, field service, a shared inbox and accounting with GST — licensed module by module, never duplicating a customer, an item or an invoice.",
    category: "B2B · SMB operating platform",
    audience: "Growing businesses outgrowing spreadsheets and a pile of disconnected apps",
    geography: "India-first (GST-native), architecture is region-agnostic",
    stage: "Live platform · five modules, paid plans in readiness review",
    url: "https://ark.wonderapps.biz/",
    helpUrl: "https://ark.wonderapps.biz/help",
    accent: "oklch(0.605 0.217 257)",
    accentSoft: "oklch(0.94 0.035 257)",
    hero: {
      headline: "One login. Every part of your business. Zero duplicate data.",
      sub: "WonderArk replaces the pile of disconnected apps a growing business ends up with — discovery, marketing, fundraising, inventory, field service, a shared inbox and accounting with GST — with one portal where every module already knows your customers, your items and your team.",
    },
    problem: {
      title: "Growth turns into a pile of tools.",
      lede: "A business that starts on spreadsheets ends up with a CRM, an inventory app, a field-service tool, a chat inbox and a GST portal — five logins, five customer records, five inventory counts.",
      points: [
        { title: "Duplicate everything", body: "The same customer exists in the CRM, the invoicing tool and the WhatsApp inbox, with three different phone numbers." },
        { title: "Stock that disagrees", body: "The count in the inventory app never matches the parts a field crew actually used on a job." },
        { title: "Compliance by re-entry", body: "GST returns, e-invoices and e-way bills are re-keyed from sales data that already exists somewhere else." },
        { title: "Integration tax", body: "Every 'integration' is an export, an import and a person who owns the spreadsheet in between." },
      ],
    },
    solution: {
      title: "One portal. One account. Five modules. One truth.",
      lede: "A strictly bounded modular platform: a shared core schema owns every cross-module noun — parties, items, documents, payments, messages — and each module owns only what is genuinely its own.",
      pillars: [
        { title: "Discovery, Marketing & Funding", body: "Per business offering, AI builds the ideal customer profile, finds and scores real accounts and explains why now. Marketing (strategy, campaigns, AI content, SEO, analytics) and Funding (investor pipeline, readiness, data room, diligence) sit on the same data. AI researches; humans approve every outreach." },
        { title: "Inventory & Service", body: "Multi-warehouse stock, purchase and sales orders, returns; opportunity-to-job pipeline, crew dispatch calendar, mobile field work with time, notes and signatures, and job invoicing that consumes stock." },
        { title: "CRM", body: "A unified inbox across WhatsApp, email and more, routing rules, lead lifecycle and a follow-up queue — tied to the same customer record every other module uses." },
        { title: "Finance & GST", body: "Automatic posting from sales and purchases, statements with drill-down to the source document, cash flow, bank rules and reporting dimensions — and GST returns computed from actual sales data rather than re-entered." },
        { title: "A team, not a login", body: "Business-scoped roles and invitations, with every action checked against both the module licence and the person's permission. Every module exports to CSV or Excel." },
      ],
    },
    howItWorks: [
      { step: "Create the business once", body: "One signup, one login, one business record — or several businesses under one account." },
      { step: "License modules independently", body: "Start with one. Add or drop later. Cancelling never deletes data: a 30-day read-only grace, then rows are retained for reactivation." },
      { step: "Data connects automatically", body: "A prospect won in Discovery is the customer in Service. Parts consumed on a job move stock in Inventory. The invoice feeds GST." },
      { step: "Ask the platform", body: "A built-in assistant answers from live data across every module you have licensed, grounded in real records." },
    ],
    screens: [
      { src: "/screenshots/wonderark/home-desktop.webp", alt: "WonderArk landing page on desktop with the new brand: one login, every part of your business, zero duplicate data", kind: "desktop", caption: "Business in one place — the new WonderArk identity" },
      { src: "/screenshots/wonderark/home-mobile.webp", alt: "WonderArk landing on a phone", kind: "mobile", caption: "Responsive across devices" },
      { src: "/screenshots/wonderark/modules-desktop.webp", alt: "WonderArk Discovery module: scored prospects per offering, with Marketing and Funding alongside", kind: "desktop", caption: "Discovery now finds customers, markets to them and funds the growth" },
      { src: "/screenshots/wonderark/pricing-mobile.webp", alt: "WonderArk pricing on a phone: Free, Pro at ₹2,999 a month, Max at ₹9,999 a month", kind: "mobile", caption: "Published pricing in rupees" },
      { src: "/screenshots/wonderark/how-it-works-desktop.webp", alt: "WonderArk how-it-works: create the business once, license modules independently, data connects automatically", kind: "desktop", caption: "License what you need; add modules in place" },
    ],
    market: {
      title: "The mid-market between spreadsheets and SAP.",
      lede: "Businesses with a warehouse, a field crew, a sales pipeline and a tax identity — trades, distributors, installers, service companies — are too complex for a single-purpose app and too small for an enterprise suite. India's GST regime makes structured, compliant data non-optional.",
      segments: ["Field-service and installation businesses", "Distributors and traders managing multi-warehouse stock", "Founder-led B2B companies building their first pipeline", "Any GST-registered business filing from real sales data"],
      whyNow: [
        "E-invoicing and e-way bill mandates keep widening the set of businesses that must operate from clean, connected data.",
        "AI makes prospect research and multi-module querying practical for a business with no analyst.",
        "Modular licensing lets a customer start small and expand in place — the land-and-expand motion vertical SaaS lacks.",
      ],
    },
    businessModel: {
      title: "License by module. Expand in place.",
      lede: "Published pricing in Indian Rupees: Free, Pro at ₹2,999/month and Max at ₹9,999/month, plus AI credit packs (₹1,000 for 500 runs up to ₹6,000 for 4,000) or bring-your-own-key. Razorpay and Stripe billing is built and in its production-readiness review, so Pro and Max are sold by conversation today. Enforcement is four layers deep — RLS, route guard, server action and UI — so an unlicensed module is genuinely off, not merely hidden.",
      plans: [
        { name: "Free", tagline: "Start with discovery", bullets: ["Core discovery tools at no cost", "One login, one business", "Team members with roles and permissions"] },
        { name: "Pro", tagline: "₹2,999 / month", featured: true, bullets: ["Every module, more usage headroom", "Up to 200 AI runs a month per Discovery offering", "Cancel a module any time: 30 days read-only, data never deleted"] },
        { name: "Max", tagline: "₹9,999 / month", bullets: ["Highest limits and every feature", "For teams running at scale", "Credit packs or your own AI key on top"] },
      ],
    },
    moat: [
      { title: "The entity-ownership map", body: "A prospect, a customer and a supplier are one party row with several roles. An estimate, an invoice and a purchase order are one documents table. This anti-duplication contract is the product." },
      { title: "Proven components, new chassis", body: "Discovery is ported from a working GTM product; Inventory and the GST engine from a working operations product. Service is built fresh against a well-documented reference category." },
      { title: "Cancel-safe by design", body: "Licensing never deletes data and reactivation replays parked events — the confidence a business needs to try a module." },
    ],
    traction: [
      { label: "Stories complete", value: "509 / 616", note: "87% of in-scope work; 30 superseded and 3 deferred stories excluded. A story counts only when code cites it" },
      { label: "Modules", value: "5 on one schema", note: "Discovery (with Marketing and Funding), Inventory, Service, CRM, Finance — independently licensable" },
      { label: "Exports", value: "Every module", note: "CSV and Excel across all modules and platform admin — 89 of 90 export stories done" },
      { label: "Team access", value: "39 of 39", note: "Multi-user, multi-business roles and invitations, enforced alongside licensing" },
    ],
    roadmap: [
      { horizon: "Now", items: ["Billing production-readiness review, then self-serve paid plans", "Global tax: VAT/GST for UAE, Saudi Arabia, Australia, NZ and Southeast Asia", "Platform administration portal (26 stories left)"] },
      { horizon: "Next", items: ["E-invoice and e-way bill transaction lists and their exports", "Finish the offering-centric Discovery upgrade (6 stories left)", "CRM channel connectors (WhatsApp, email)"] },
      { horizon: "Later", items: ["Public API and partner integrations", "Independent deployability per module as scale demands"] },
    ],
    ask: "Seeking design customers in field service and distribution, and investors who understand vertical SaaS in India's GST-native SMB market.",
    facts: [
      { label: "Platform", value: "Web · responsive · mobile-friendly field work" },
      { label: "AI", value: "OpenAI, Anthropic, Google — BYOK or platform key" },
      { label: "Data", value: "Supabase PostgreSQL, schema-per-module, RLS tenant AND licensed" },
      { label: "Pricing", value: "Free · Pro (per module) · Max (bundle)" },
    ],
  },
  {
    slug: "wonderid",
    name: "WonderID",
    tagline: "Secure every identity. Human and AI.",
    oneLiner:
      "Vendor-neutral identity governance for everything that holds access — people, service accounts, applications and AI agents — starting with the identity nobody governs yet: the AI agent.",
    category: "Enterprise · Identity governance & security",
    audience: "CISOs, IAM and GRC teams governing people, machines and AI agents",
    geography: "Global enterprise",
    stage: "Live multi-tenant platform · formerly WonderAgent",
    url: "https://agent.wonderapps.biz/",
    helpUrl: "https://agent.wonderapps.biz/help",
    accent: "oklch(0.563 0.24 264)",
    accentSoft: "oklch(0.93 0.04 264)",
    logo: { light: "/brands/wonderid/wonderid-logo-light.webp", dark: "/brands/wonderid/wonderid-logo-dark.webp", mark: "/brands/wonderid/wonderid-mark.webp" },
    hero: {
      headline: "Govern every identity. Verify every access.",
      sub: "People, service accounts and AI agents all hold real access to real systems. WonderID makes each one a governed identity — starting with AI agents, where it compares what an agent SHOULD do, CAN do and DID, and raises an evidence-backed finding the moment they disagree. Read-only to start; your IAM stays the system of record.",
    },
    problem: {
      title: "AI agents got production access. Nobody gave them an identity.",
      lede: "An agent is provisioned like a service account, inherits access like a person, and acts continuously like neither. Most exist as untracked service accounts — alongside the people and machines no one has reconciled either.",
      points: [
        { title: "No owner", body: "Provisioned as SVC_FINANCEBOT_PRD by someone who has since changed teams. No business owner, no technical owner, nobody to approve a change." },
        { title: "Purpose that no control can read", body: "The agent's approved scope lives in a ticket, a design doc or someone's memory — never anywhere a control can evaluate." },
        { title: "Access far beyond purpose", body: "Nested groups, OAuth scopes and tool permissions add up to reach that nobody has computed, let alone certified." },
        { title: "Behaviour disconnected from identity", body: "Runtime logs sit in an observability tool keyed by service name, cut off from the entitlement and approval that allowed the action." },
      ],
    },
    solution: {
      title: "SHOULD. CAN. DID. — then every identity around it.",
      lede: "Agent governance stays at its core; the same deterministic engine now extends to a unified identity directory, application onboarding and self-service access — across the IAM platforms a customer already runs (Saviynt, Okta, Entra, custom IAM and MCP runtimes map into one canonical model).",
      pillars: [
        { title: "AI agent governance", body: "Every agent gets an owner, a purpose contract and a lifecycle state. Its approved purpose (SHOULD), effective access computed from real entitlements, roles, groups and OAuth scopes (CAN), and observed runtime behaviour (DID) are compared continuously; any divergence is a finding with evidence." },
        { title: "One directory for every identity", body: "Humans, external users, service accounts, applications, workloads, APIs and AI agents in one tenant-scoped directory — fed by authoritative sources through a validate, correlate, stage and apply reconciliation pipeline, with joiner, mover and leaver lifecycle." },
        { title: "Applications, onboarded properly", body: "An application catalog that surfaces unrecognised apps, onboarding that validates, simulates and needs a four-eyes approval before it goes live, and an account inventory that flags orphaned and dormant accounts. AI can draft an onboarding proposal from an OpenAPI spec; a person approves it." },
        { title: "Self-service access, real approvals", body: "A request catalog with per-item policies, multi-stage approval chains that forbid self-approval, and access packages that work the same for people and agents." },
        { title: "Risk, certification & evidence", body: "Deterministic scoring — never an LLM guess — for excessive access, unauthorised actions, sensitive-data violations and behavioural deviation. Certification campaigns produce auditor-ready evidence packs." },
      ],
    },
    howItWorks: [
      { step: "Connect", body: "Import identities, applications and access from existing IAM and authoritative sources, plus runtime events from MCP or REST. Connectors declare capabilities explicitly; read-only means read-only." },
      { step: "Declare purpose", body: "Name an owner, approved applications, approved data classes and approved actions. That contract becomes SHOULD." },
      { step: "Compare continuously", body: "Purpose, effective access and observed behaviour are evaluated by explicit rules. Findings carry the evidence that produced them." },
      { step: "Remediate with a human", body: "Every recommended revocation waits for a human to confirm, is recorded against the finding, and is re-evaluated once access changes." },
    ],
    screens: [
      { src: "/screenshots/wonderid/home-desktop.webp", alt: "WonderID product site on desktop: 'Govern every identity. Verify every access.' above a tenant overview", kind: "desktop", caption: "The product site — every identity governed, starting with AI agents" },
      { src: "/screenshots/wonderid/home-mobile.webp", alt: "WonderID product site on a phone with the tenant overview preview", kind: "mobile", caption: "The same, on a phone" },
      { src: "/screenshots/wonderid/product-desktop.webp", alt: "WonderID risk list ordered by severity and the governed AI agent inventory", kind: "desktop", caption: "Risk ordered by what to do first; an agent inventory that is actually governed" },
      { src: "/screenshots/wonderid/signin-mobile.webp", alt: "WonderID sign-in on a phone with email, Google and SSO options", kind: "mobile", caption: "Sign in with email, Google or enterprise SSO" },
      { src: "/screenshots/wonderid/model-desktop.webp", alt: "WonderID SHOULD, CAN and DID comparison raising an excessive-access finding for FinanceBot", kind: "desktop", caption: "SHOULD · CAN · DID — a critical finding, with the evidence attached" },
      { src: "/screenshots/wonderid/model-mobile.webp", alt: "WonderID SHOULD, CAN and DID model on a phone", kind: "mobile", caption: "The governance model, on mobile" },
      { src: "/screenshots/wonderid/platform-desktop.webp", alt: "WonderID platform capabilities: agent lifecycle, effective access, runtime assurance, risk, certification and IAM integration", kind: "desktop", caption: "A governance layer over the IAM you already run" },
      { src: "/screenshots/wonderid/signin-desktop.webp", alt: "WonderID sign-in page with the new brand lockup", kind: "desktop", caption: "The WonderID brand, rolled out across every surface" },
    ],
    market: {
      title: "Every identity is an attack surface — and most of them aren't people.",
      lede: "Enterprise IAM was built for employees. Service accounts, workloads and APIs already sprawl beyond them, and AI agents add autonomy on top. Security leaders need one answer to 'who and what has access, who owns it, why, and what did they do with it?' — and proof for auditors.",
      segments: ["Regulated enterprises in finance, healthcare and public sector", "Organisations rolling out MCP-based agent platforms", "IAM/IGA teams consolidating human, machine and agent identity governance", "GRC teams facing AI-specific audit requirements"],
      whyNow: [
        "Agent adoption is outpacing governance; MCP has standardised how agents reach tools, which makes runtime observation tractable.",
        "Regulators and auditors are asking for demonstrable control over AI systems, not policy documents.",
        "Incumbent IGA suites are strong on human identity and bolt agents on; a vendor-neutral layer that starts from the agent and keeps existing IAM as system of record is the low-friction path in.",
      ],
    },
    businessModel: {
      title: "Enterprise SaaS, priced per tenant.",
      lede: "Multi-tenant from day one with a separate vendor-only platform-admin boundary for tenants, subscriptions, feature flags, usage and health. Deployment-ready today; commercial packaging follows the first design customers.",
      plans: [
        { name: "Pilot", tagline: "Read-only proof", bullets: ["Connect one IAM and one runtime source", "Discover and register agents", "First risk findings and a certification round"] },
        { name: "Enterprise", tagline: "Governance in production", featured: true, bullets: ["Unlimited identities and integrations", "Identity directory, application onboarding and self-service access", "SSO/MFA, scoped roles and permissions", "Certification, evidence packs and human-confirmed remediation"] },
      ],
    },
    moat: [
      { title: "Agent-first, identity-wide", body: "Incumbent suites bolt agents onto a human model. WonderID started from the agent — owner, purpose, effective access, observed behaviour — and extends outward, so an AI agent is a first-class identity rather than a column on a service-account table." },
      { title: "Deterministic by architecture", body: "No authorisation, risk, policy or remediation decision depends on a language model. AI writes advisory summaries and proposals only. That is an auditable promise competitors chasing 'AI security' cannot easily make." },
      { title: "Vendor-neutral canonical model", body: "Saviynt, SailPoint, Entra, Okta, custom IAM and MCP map into one model without any becoming the internal architecture." },
      { title: "Built to enterprise bar from line one", body: "Tenant RLS on every table, server-side tenant context, immutable audit, encrypted credentials, CSP headers, rate-limited auth — verified by a dedicated QA module." },
    ],
    traction: [
      { label: "Stories complete", value: "187 / 239", note: "78% across 11 modules; the tracker grew by 74 stories when WonderID's identity roadmap was adopted" },
      { label: "WonderID roadmap", value: "14 of 36 done", note: "Identity directory, reconciliation, application onboarding, account inventory, requests, approvals and access packages shipped; 4 more partial" },
      { label: "API surface", value: "168 routes", note: "143 call requirePermission directly; 100 database migrations" },
      { label: "Screens", value: "78 + 8", note: "Customer pages plus the vendor platform-admin console" },
    ],
    roadmap: [
      { horizon: "Now", items: ["Business and IT roles, preventive SoD and delegations", "Provisioning and deprovisioning pipeline", "Access ledger, imported-access classification and Rogue Access management"] },
      { horizon: "Next", items: ["Certification campaigns for every identity type", "Passkey (WebAuthn) sign-in and step-up", "WonderID Home and a My Access self-service portal"] },
      { horizon: "Later", items: ["Configuration Studio and a workflow designer", "An advisory-only WonderID AI assistant", "Partner and MSSP editions"] },
    ],
    ask: "Seeking two to three enterprise design partners with agents in production or an identity estate to consolidate, and investors focused on security and identity infrastructure.",
    facts: [
      { label: "Platform", value: "Web · responsive · vendor platform-admin console" },
      { label: "AI", value: "Advisory summaries only — OpenAI / Gemini, platform or BYOK" },
      { label: "Data", value: "Supabase PostgreSQL, tenant_id + RLS on every table" },
      { label: "Pricing", value: "Pilot · Enterprise (packaging with design partners)" },
    ],
  },
];

export const startupBySlug = (slug: string) => startups.find((s) => s.slug === slug);
